export const asfScienceQuizzes = [
  {
    exercise: "Everyday Science - Set 1",
    questions: [
      { q: "The powerhouse of the cell is:", options: ["Nucleus", "Mitochondria", "Ribosome", "Cytoplasm"], correct: 1 },
      { q: "The SI unit of force is:", options: ["Joule", "Newton", "Watt", "Pascal"], correct: 1 },
      { q: "Which gas is most abundant in air?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 2 },
      { q: "Vitamin C deficiency causes:", options: ["Rickets", "Scurvy", "Night blindness", "Beriberi"], correct: 1 },
      { q: "Which planet is called the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], correct: 1 },
      { q: "The human heart has how many chambers?", options: ["2", "3", "4", "5"], correct: 2 },
      { q: "Which organ purifies blood in the human body?", options: ["Liver", "Heart", "Kidneys", "Lungs"], correct: 2 },
      { q: "The boiling point of water is:", options: ["50°C", "100°C", "150°C", "0°C"], correct: 1 },
      { q: "The unit of electric current is:", options: ["Volt", "Ampere", "Ohm", "Watt"], correct: 1 },
      { q: "The ozone layer protects us from:", options: ["Infrared rays", "UV rays", "X-rays", "Sound waves"], correct: 1 },
      { q: "Which is the largest planet in the solar system?", options: ["Earth", "Saturn", "Jupiter", "Neptune"], correct: 2 },
      { q: "The normal human body temperature is:", options: ["35°C", "37°C", "40°C", "42°C"], correct: 1 },
      { q: "Which vitamin is produced in sunlight exposure?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 3 },
      { q: "The basic unit of life is:", options: ["Tissue", "Organ", "Cell", "System"], correct: 2 },
      { q: "Which gas do plants absorb?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
      { q: "Speed is equal to:", options: ["Distance × Time", "Distance / Time", "Time / Distance", "Mass × Acceleration"], correct: 1 },
      { q: "The Earth revolves around the:", options: ["Moon", "Sun", "Mars", "Venus"], correct: 1 },
      { q: "The gas used in balloons is:", options: ["Oxygen", "Nitrogen", "Helium", "Carbon dioxide"], correct: 2 },
      { q: "Which organ controls the human body?", options: ["Heart", "Brain", "Liver", "Kidney"], correct: 1 },
      { q: "The hardest natural substance is:", options: ["Gold", "Iron", "Diamond", "Silver"], correct: 2 },
      { q: "Which is a renewable source of energy?", options: ["Coal", "Petroleum", "Solar energy", "Natural gas"], correct: 2 },
      { q: "The speed of light is:", options: ["3 × 10⁸ m/s", "3 × 10⁶ m/s", "3 × 10⁵ m/s", "3 × 10⁷ m/s"], correct: 0 },
      { q: "Photosynthesis occurs in:", options: ["Animals", "Plants", "Humans", "Fungi"], correct: 1 },
      { q: "Which gas is used in fire extinguishers?", options: ["Oxygen", "Carbon dioxide", "Hydrogen", "Nitrogen"], correct: 1 },
      { q: "The chemical formula of water is:", options: ["CO₂", "H₂O", "O₂", "NaCl"], correct: 1 }
    ]
  },
  {
    exercise: "Everyday Science - Set 2",
    questions: [
      { q: "The Earth is known as the:", options: ["Red planet", "Blue planet", "Hot planet", "Gas planet"], correct: 1 },
      { q: "Which organ helps in breathing?", options: ["Liver", "Lungs", "Heart", "Kidney"], correct: 1 },
      { q: "The smallest bone in the human body is in:", options: ["Ear", "Leg", "Hand", "Skull"], correct: 0 },
      { q: "The force that pulls objects toward Earth is:", options: ["Magnetism", "Friction", "Gravity", "Pressure"], correct: 2 },
      { q: "Which is a fossil fuel?", options: ["Wind", "Solar", "Coal", "Water"], correct: 2 },
      { q: "Which organ pumps blood in the human body?", options: ["Brain", "Heart", "Liver", "Kidney"], correct: 1 },
      { q: "The unit of power is:", options: ["Joule", "Watt", "Newton", "Pascal"], correct: 1 },
      { q: "Which planet is nearest to the Sun?", options: ["Venus", "Mercury", "Earth", "Mars"], correct: 1 },
      { q: "Which gas do humans breathe in?", options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"], correct: 2 },
      { q: "The study of plants is called:", options: ["Zoology", "Botany", "Biology", "Ecology"], correct: 1 },
      { q: "Which blood cells fight infections?", options: ["Red blood cells", "White blood cells", "Platelets", "Plasma"], correct: 1 },
      { q: "The chemical symbol of oxygen is:", options: ["O", "Ox", "O2", "Om"], correct: 0 },
      { q: "The largest organ in the human body is:", options: ["Heart", "Skin", "Liver", "Brain"], correct: 1 },
      { q: "Which planet is known as the Blue Planet?", options: ["Mars", "Earth", "Venus", "Neptune"], correct: 1 },
      { q: "The Earth has how many continents?", options: ["5", "6", "7", "8"], correct: 2 },
      { q: "Sound travels fastest in:", options: ["Air", "Water", "Vacuum", "Solid"], correct: 3 },
      { q: "The SI unit of energy is:", options: ["Newton", "Watt", "Joule", "Volt"], correct: 2 },
      { q: "Which vitamin is good for eyesight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 0 },
      { q: "The process of water changing into vapor is called:", options: ["Condensation", "Evaporation", "Freezing", "Melting"], correct: 1 },
      { q: "The Earth takes how long to rotate once?", options: ["12 hours", "24 hours", "30 days", "365 days"], correct: 1 },
      { q: "Which is the main gas in LPG?", options: ["Methane", "Propane", "Butane", "Oxygen"], correct: 2 },
      { q: "The brain is part of the:", options: ["Digestive system", "Nervous system", "Respiratory system", "Circulatory system"], correct: 1 },
      { q: "The SI unit of length is:", options: ["Meter", "Kilometer", "Gram", "Liter"], correct: 0 },
      { q: "Which metal is liquid at room temperature?", options: ["Iron", "Mercury", "Gold", "Silver"], correct: 1 },
      { q: "The main source of energy on Earth is:", options: ["Moon", "Sun", "Wind", "Water"], correct: 1 }
    ]
  },
  {
    exercise: "Everyday Science - Set 3",
    questions: [
      { q: "Which organ helps in digestion?", options: ["Lungs", "Heart", "Stomach", "Brain"], correct: 2 },
      { q: "Water boils at sea level at:", options: ["90°C", "80°C", "100°C", "120°C"], correct: 2 },
      { q: "The red pigment in blood is:", options: ["Plasma", "Hemoglobin", "Platelets", "Oxygen"], correct: 1 },
      { q: "Which is a non-renewable resource?", options: ["Solar energy", "Wind energy", "Coal", "Water"], correct: 2 },
      { q: "Which gas causes global warming most?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
      { q: "Which part of plant makes food?", options: ["Root", "Stem", "Leaf", "Flower"], correct: 2 },
      { q: "The Earth revolves around the Sun in:", options: ["30 days", "100 days", "365 days", "24 hours"], correct: 2 },
      { q: "Which organ filters blood?", options: ["Heart", "Kidney", "Liver", "Brain"], correct: 1 },
      { q: "Light travels in:", options: ["Waves", "Curves", "Straight lines", "Circles"], correct: 2 },
      { q: "The gas used for respiration by humans is:", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Helium"], correct: 1 },
      { q: "The basic unit of matter is:", options: ["Cell", "Atom", "Molecule", "Compound"], correct: 1 },
      { q: "Which gas is used in soft drinks?", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Hydrogen"], correct: 1 },
      { q: "The process by which plants lose water is called:", options: ["Evaporation", "Transpiration", "Condensation", "Respiration"], correct: 1 },
      { q: "Which organ controls balance in the human body?", options: ["Brain", "Ear", "Heart", "Liver"], correct: 1 },
      { q: "The chemical symbol of iron is:", options: ["Ir", "Fe", "In", "I"], correct: 1 },
      { q: "Which planet has rings?", options: ["Earth", "Mars", "Saturn", "Mercury"], correct: 2 },
      { q: "The study of animals is called:", options: ["Botany", "Zoology", "Ecology", "Geology"], correct: 1 },
      { q: "The SI unit of temperature is:", options: ["Celsius", "Kelvin", "Fahrenheit", "Joule"], correct: 1 },
      { q: "Which vitamin is known as sunshine vitamin?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 3 },
      { q: "The human skeleton is made of:", options: ["Muscles", "Bones", "Blood", "Skin"], correct: 1 },
      { q: "Which organ is responsible for pumping blood?", options: ["Kidney", "Brain", "Heart", "Liver"], correct: 2 },
      { q: "The Earth is surrounded by a layer of gases called:", options: ["Lithosphere", "Atmosphere", "Hydrosphere", "Biosphere"], correct: 1 },
      { q: "Which is the lightest gas?", options: ["Oxygen", "Nitrogen", "Hydrogen", "Helium"], correct: 2 },
      { q: "The largest ocean on Earth is:", options: ["Atlantic", "Indian", "Pacific", "Arctic"], correct: 2 },
      { q: "Which organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Heart"], correct: 1 }
    ]
  },
  {
    exercise: "Everyday Science - Set 4",
    questions: [
      { q: "Sound cannot travel through:", options: ["Air", "Water", "Solid", "Vacuum"], correct: 3 },
      { q: "Which metal is used in electrical wires?", options: ["Iron", "Copper", "Gold", "Silver"], correct: 1 },
      { q: "The Earth is shaped like a:", options: ["Square", "Circle", "Sphere", "Triangle"], correct: 2 },
      { q: "The process of solid turning into liquid is:", options: ["Freezing", "Melting", "Evaporation", "Condensation"], correct: 1 },
      { q: "Which organ helps in breathing?", options: ["Heart", "Lungs", "Liver", "Kidney"], correct: 1 },
      { q: "Which gas is essential for burning?", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"], correct: 1 },
      { q: "The SI unit of mass is:", options: ["Gram", "Kilogram", "Newton", "Liter"], correct: 1 },
      { q: "Which planet is closest to Earth?", options: ["Mars", "Venus", "Mercury", "Jupiter"], correct: 1 },
      { q: "The human body has how many lungs?", options: ["1", "2", "3", "4"], correct: 1 },
      { q: "Which organ removes waste from blood?", options: ["Heart", "Kidney", "Brain", "Stomach"], correct: 1 },
      { q: "The main gas in Earth’s atmosphere is:", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 1 },
      { q: "Which organ helps in thinking?", options: ["Heart", "Brain", "Liver", "Kidney"], correct: 1 },
      { q: "The freezing point of water is:", options: ["0°C", "50°C", "100°C", "10°C"], correct: 0 },
      { q: "Which energy is produced by the Sun?", options: ["Chemical energy", "Solar energy", "Nuclear energy", "Wind energy"], correct: 1 },
      { q: "Which blood cells help in clotting?", options: ["RBCs", "WBCs", "Platelets", "Plasma"], correct: 2 },
      { q: "The SI unit of work is:", options: ["Watt", "Newton", "Joule", "Pascal"], correct: 2 },
      { q: "Which organ is called the 'control center' of the body?", options: ["Heart", "Brain", "Liver", "Kidney"], correct: 1 },
      { q: "Which gas is responsible for global warming?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
      { q: "The study of living organisms is called:", options: ["Physics", "Biology", "Geology", "Astronomy"], correct: 1 },
      { q: "The basic building block of proteins is:", options: ["Fat", "Amino acids", "Glucose", "Vitamins"], correct: 1 },
      { q: "The hardest natural substance is:", options: ["Gold", "Iron", "Diamond", "Silver"], correct: 2 },
      { q: "Which organ helps in digestion of food?", options: ["Heart", "Stomach", "Brain", "Lung"], correct: 1 },
      { q: "The Earth’s natural satellite is:", options: ["Sun", "Mars", "Moon", "Venus"], correct: 2 },
      { q: "Which vitamin prevents rickets?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 3 },
      { q: "The SI unit of force is:", options: ["Joule", "Newton", "Watt", "Ampere"], correct: 1 }
    ]
  },
  {
    exercise: "Everyday Science - Set 5",
    questions: [
      { q: "Which planet is known as Earth’s twin?", options: ["Mars", "Venus", "Mercury", "Jupiter"], correct: 1 },
      { q: "Blood is pumped by the:", options: ["Brain", "Liver", "Heart", "Kidney"], correct: 2 },
      { q: "Which gas is essential for burning?", options: ["Nitrogen", "Oxygen", "Carbon dioxide", "Hydrogen"], correct: 1 },
      { q: "The process of cell division is called:", options: ["Photosynthesis", "Mitosis", "Respiration", "Fermentation"], correct: 1 },
      { q: "Which part of the plant absorbs water?", options: ["Leaf", "Flower", "Root", "Stem"], correct: 2 },
      { q: "The SI unit of electric current is:", options: ["Volt", "Watt", "Ampere", "Ohm"], correct: 2 },
      { q: "The Earth revolves around the Sun in:", options: ["30 days", "365 days", "24 hours", "12 hours"], correct: 1 },
      { q: "Which organ removes waste from blood?", options: ["Heart", "Kidney", "Brain", "Liver"], correct: 1 },
      { q: "The atmosphere is mainly made of:", options: ["Oxygen", "Hydrogen", "Nitrogen", "Carbon dioxide"], correct: 2 },
      { q: "Which planet is the largest?", options: ["Earth", "Mars", "Jupiter", "Venus"], correct: 2 },
      { q: "Sound cannot travel through:", options: ["Air", "Water", "Solid", "Vacuum"], correct: 3 },
      { q: "The study of rocks is called:", options: ["Biology", "Geology", "Zoology", "Ecology"], correct: 1 },
      { q: "Which blood cells fight infection?", options: ["RBCs", "WBCs", "Platelets", "Plasma"], correct: 1 },
      { q: "The chemical formula of salt is:", options: ["H₂O", "NaCl", "CO₂, O₂"], correct: 1 },
      { q: "Which planet is known as the 'Red Planet'?", options: ["Venus", "Mars", "Mercury", "Jupiter"], correct: 1 },
      { q: "The human body has how many lungs?", options: ["1", "2", "3", "4"], correct: 1 },
      { q: "Which organ produces bile?", options: ["Kidney", "Liver", "Heart", "Lung"], correct: 1 },
      { q: "The freezing point of water is:", options: ["0°C", "50°C", "100°C", "10°C"], correct: 0 },
      { q: "Which energy comes from the Sun?", options: ["Nuclear", "Solar", "Chemical", "Mechanical"], correct: 1 },
      { q: "The process of converting liquid into gas is called:", options: ["Freezing", "Evaporation", "Condensation", "Melting"], correct: 1 },
      { q: "Which organ is responsible for pumping blood?", options: ["Brain", "Heart", "Liver", "Kidney"], correct: 1 },
      { q: "The SI unit of energy is:", options: ["Newton", "Watt", "Joule", "Pascal"], correct: 2 },
      { q: "Which gas do humans exhale?", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 2 },
      { q: "The study of matter is called:", options: ["Biology", "Physics", "Chemistry", "Geology"], correct: 1 },
      { q: "Which vitamin is produced in sunlight?", options: ["Vitamin A", "Vitamin B", "Vitamin C", "Vitamin D"], correct: 3 }
    ]
  },
  {
    exercise: "Everyday Science - Set 6",
    questions: [
      { q: "The largest organ in the human body is:", options: ["Liver", "Skin", "Heart", "Brain"], correct: 1 },
      { q: "Which planet is closest to the Sun?", options: ["Earth", "Mercury", "Venus", "Mars"], correct: 1 },
      { q: "The human body has how many bones?", options: ["206", "201", "210", "250"], correct: 0 },
      { q: "The chemical symbol of sodium is:", options: ["So", "Na", "Sd", "Sm"], correct: 1 },
      { q: "Which organ helps in breathing?", options: ["Heart", "Lungs", "Kidney", "Liver"], correct: 1 },
      { q: "The SI unit of force is:", options: ["Joule", "Newton", "Watt", "Volt"], correct: 1 },
      { q: "Which planet is known as the 'Blue Planet'?", options: ["Mars", "Venus", "Earth", "Jupiter"], correct: 2 },
      { q: "The process of plants making food is called:", options: ["Respiration", "Digestion", "Photosynthesis", "Fermentation"], correct: 2 },
      { q: "The main gas in Earth’s atmosphere is:", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Hydrogen"], correct: 1 },
      { q: "Which organ filters blood?", options: ["Heart", "Liver", "Kidney", "Brain"], correct: 2 },
      { q: "The SI unit of length is:", options: ["Kilogram", "Meter", "Gram", "Liter"], correct: 1 },
      { q: "Which is a renewable energy source?", options: ["Coal", "Oil", "Solar", "Gas"], correct: 2 },
      { q: "The boiling point of water is:", options: ["0°C", "50°C", "100°C", "120°C"], correct: 2 },
      { q: "Which blood cells fight diseases?", options: ["RBCs", "WBCs", "Platelets", "Plasma"], correct: 1 },
      { q: "The Earth takes how long to rotate once?", options: ["12 hours", "24 hours", "30 days", "365 days"], correct: 1 },
      { q: "Which organ controls the body?", options: ["Heart", "Brain", "Liver", "Kidney"], correct: 1 },
      { q: "Which gas is used in balloons?", options: ["Oxygen", "Helium", "Carbon dioxide", "Hydrogen"], correct: 1 },
      { q: "The freezing point of water is:", options: ["10°C", "50°C", "0°C", "100°C"], correct: 2 },
      { q: "Which planet is called the Red Planet?", options: ["Venus", "Mars", "Jupiter", "Mercury"], correct: 1 },
      { q: "The smallest unit of life is:", options: ["Tissue", "Organ", "Cell", "System"], correct: 2 },
      { q: "Sound travels fastest in:", options: ["Air", "Water", "Solid", "Vacuum"], correct: 2 },
      { q: "The chemical formula of water is:", options: ["CO₂", "H₂O", "O₂", "NaCl"], correct: 1 },
      { q: "Which organ produces insulin?", options: ["Liver", "Pancreas", "Kidney", "Heart"], correct: 1 },
      { q: "Which planet has rings?", options: ["Earth", "Mars", "Saturn", "Venus"], correct: 2 },
      { q: "The process of liquid turning into gas is called:", options: ["Condensation", "Evaporation", "Freezing", "Melting"], correct: 1 }
    ]
  }
];
