export const biologyClass11Quizzes = [
  {
    exercise: "Chapter 1: Cell Structure and Function",
    questions: [
      { q: "The term “cell” was first used by Robert Hooke after observing cork under a microscope because he noticed:", options: ["Living cytoplasm", "Honeycomb-like empty chambers", "Moving organelles", "Dividing nuclei"], correct: 1 },
      { q: "The cell theory was independently proposed by Matthias Schleiden and Theodor Schwann and states that:", options: ["Cells arise spontaneously", "All organisms are composed of one or more cells", "Cells are non-living", "Only plants are cellular"], correct: 1 },
      { q: "The modern cell theory additionally states that new cells arise from:", options: ["Non-living matter", "Pre-existing cells", "Cytoplasm only", "Nucleus fragmentation"], correct: 1 },
      { q: "Prokaryotic cells differ from eukaryotic cells primarily because prokaryotes:", options: ["Lack cytoplasm", "Lack membrane-bound organelles", "Lack DNA", "Lack ribosomes"], correct: 1 },
      { q: "The plasma membrane is described as selectively permeable because it:", options: ["Allows all substances to pass freely", "Prevents all movement", "Regulates movement of substances in and out", "Is composed of cellulose"], correct: 2 },
      { q: "According to the fluid mosaic model, the plasma membrane consists mainly of:", options: ["Carbohydrate bilayer", "Phospholipid bilayer with embedded proteins", "Protein bilayer with lipids inside", "DNA and enzymes"], correct: 1 },
      { q: "The hydrophobic region of a phospholipid is formed by:", options: ["Phosphate head", "Glycerol backbone", "Fatty acid tails", "Carbohydrate chain"], correct: 2 },
      { q: "Ribosomes are the site of:", options: ["Lipid synthesis", "Protein synthesis", "DNA replication", "ATP storage"], correct: 1 },
      { q: "The endoplasmic reticulum that is studded with ribosomes is called:", options: ["Smooth ER", "Rough ER", "Golgi apparatus", "Lysosome"], correct: 1 },
      { q: "Smooth endoplasmic reticulum is mainly involved in:", options: ["Protein synthesis", "Lipid synthesis and detoxification", "DNA packaging", "Cell division"], correct: 1 },
      { q: "The Golgi apparatus modifies and packages proteins primarily by:", options: ["Synthesizing amino acids", "Phosphorylating lipids", "Forming secretory vesicles", "Replicating DNA"], correct: 2 },
      { q: "Lysosomes contain hydrolytic enzymes that function best at:", options: ["Neutral pH", "Acidic pH", "Basic pH", "High temperature"], correct: 1 },
      { q: "Mitochondria are called the powerhouse of the cell because they:", options: ["Store DNA", "Generate ATP through cellular respiration", "Produce ribosomes", "Synthesize lipids"], correct: 1 },
      { q: "The inner membrane of mitochondria forms folds called cristae to:", options: ["Store water", "Increase surface area for ATP production", "Protect DNA", "Transport proteins"], correct: 1 },
      { q: "Chloroplasts are present in plant cells and function primarily in:", options: ["Respiration", "Protein synthesis", "Photosynthesis", "Detoxification"], correct: 2 },
      { q: "The fluid nature of the membrane is mainly due to:", options: ["Carbohydrate chains", "Lateral movement of phospholipids", "Cell wall rigidity", "DNA content"], correct: 1 },
      { q: "The nucleus is separated from cytoplasm by a:", options: ["Cell wall", "Single membrane", "Double membrane nuclear envelope", "Protein coat"], correct: 2 },
      { q: "Nucleolus is primarily responsible for synthesis of:", options: ["Lipids", "mRNA", "Ribosomal RNA", "DNA"], correct: 2 },
      { q: "Cytoskeleton provides structural support and is composed of:", options: ["Carbohydrates", "Microtubules and microfilaments", "Lipid bilayers", "Enzymes only"], correct: 1 },
      { q: "Centrioles are mainly involved in:", options: ["Photosynthesis", "Cell division and spindle formation", "ATP synthesis", "Detoxification"], correct: 1 },
      { q: "Passive transport differs from active transport because passive transport:", options: ["Requires ATP", "Moves substances against gradient", "Moves substances along concentration gradient", "Occurs only in plants"], correct: 2 },
      { q: "Facilitated diffusion requires:", options: ["ATP", "Carrier or channel proteins", "Ribosomes", "Lysosomes"], correct: 1 },
      { q: "Osmosis is specifically defined as movement of:", options: ["Solutes", "Water across a semi-permeable membrane", "Proteins", "ATP"], correct: 1 },
      { q: "A plant cell placed in hypotonic solution becomes turgid because:", options: ["Water leaves the cell", "Solutes enter the cell", "Water enters the cell", "Membrane breaks"], correct: 2 },
      { q: "Plasmolysis occurs when:", options: ["Cell gains water", "Cell loses water in hypertonic solution", "ATP increases", "DNA replicates"], correct: 1 },
      { q: "The cell wall in plants is mainly composed of:", options: ["Chitin", "Peptidoglycan", "Cellulose", "Phospholipids"], correct: 2 },
      { q: "Prokaryotic DNA is typically located in:", options: ["Nucleus", "Nucleoid region", "Mitochondria", "Lysosome"], correct: 1 },
      { q: "The semi-fluid nature of cytoplasm allows:", options: ["Rigidity", "Constant movement of organelles", "DNA packaging", "Cell wall formation"], correct: 1 },
      { q: "Peroxisomes are involved in:", options: ["Protein synthesis", "Breakdown of hydrogen peroxide", "Photosynthesis", "DNA replication"], correct: 1 },
      { q: "Vacuoles in plant cells are important for:", options: ["ATP production", "Storage and maintenance of turgor pressure", "Ribosome synthesis", "Lipid formation"], correct: 1 },
      { q: "Active transport requires energy because it:", options: ["Moves substances down gradient", "Moves substances against concentration gradient", "Uses osmosis", "Uses diffusion only"], correct: 1 },
      { q: "The phospholipid bilayer is considered amphipathic because phospholipids:", options: ["Are entirely hydrophobic", "Have both hydrophilic and hydrophobic regions", "Contain proteins", "Contain DNA"], correct: 1 },
      { q: "Ribosomes attached to rough ER primarily synthesize proteins destined for:", options: ["Cytoplasm use only", "Secretion or membrane insertion", "Mitochondria only", "Nucleus only"], correct: 1 },
      { q: "The large central vacuole of plant cells helps maintain:", options: ["Genetic material", "Cell rigidity", "Lysosomal enzymes", "Ribosomal RNA"], correct: 1 },
      { q: "The main structural difference between plant and animal cells is the presence in plant cells of:", options: ["Ribosomes", "Plasma membrane", "Cell wall and chloroplasts", "Mitochondria"], correct: 2 },
      { q: "The endomembrane system functions cooperatively to:", options: ["Destroy DNA", "Synthesize, modify, and transport proteins", "Produce ATP", "Store lipids only"], correct: 1 },
      { q: "Surface area to volume ratio is important in cells because it affects:", options: ["DNA replication", "Efficiency of material exchange", "Ribosome formation", "ATP storage"], correct: 1 },
      { q: "If mitochondrial cristae are damaged, the most immediate effect would be reduced:", options: ["Protein synthesis", "Photosynthesis", "ATP production", "DNA replication"], correct: 2 },
      { q: "Microtubules assist in:", options: ["Lipid synthesis", "Intracellular transport and cell division", "Osmosis", "DNA mutation"], correct: 1 },
      { q: "Cilia and flagella enable cells to:", options: ["Divide", "Store water", "Move or create fluid movement", "Produce ATP"], correct: 2 },
      { q: "Tight junctions between cells primarily function to:", options: ["Allow diffusion", "Prevent leakage between cells", "Synthesize proteins", "Store ATP"], correct: 1 },
      { q: "The presence of peptidoglycan is characteristic of:", options: ["Plant cells", "Animal cells", "Bacterial cell walls", "Fungal cell walls"], correct: 2 },
      { q: "Diffusion rate increases when:", options: ["Temperature decreases", "Concentration gradient increases", "Surface area decreases", "Membrane thickens"], correct: 1 },
      { q: "The nucleus controls cellular activities because it contains:", options: ["Ribosomes", "DNA with genetic instructions", "Lipids", "Vacuoles"], correct: 1 },
      { q: "The primary function of centrosome is:", options: ["Photosynthesis", "Organizing microtubules", "Protein secretion", "Detoxification"], correct: 1 },
      { q: "Integral membrane proteins are embedded within:", options: ["Cell wall", "Lipid bilayer", "Cytoplasm", "Nucleus"], correct: 1 },
      { q: "The semi-permeability of membranes is largely due to:", options: ["Cellulose", "Phospholipid bilayer arrangement", "DNA", "Ribosomes"], correct: 1 },
      { q: "Autolysis refers to:", options: ["Cell division", "Self-digestion by lysosomal enzymes", "Photosynthesis", "Osmosis"], correct: 1 },
      { q: "The compartmentalization of eukaryotic cells increases efficiency because it:", options: ["Reduces enzyme activity", "Separates incompatible metabolic processes", "Eliminates nucleus", "Prevents protein synthesis"], correct: 1 },
      { q: "The fundamental unit of structure and function in all living organisms is the:", options: ["Tissue", "Organ", "Cell", "Organ system"], correct: 2 }
    ]
  },
  {
    exercise: "Chapter 2: Biological Molecules",
    questions: [
      { q: "The unique ability of carbon to form stable covalent bonds with itself and other elements results in the formation of large, complex molecules primarily because carbon:", options: ["Has two valence electrons", "Can form four covalent bonds and catenated chains", "Is highly electronegative", "Forms ionic compounds easily"], correct: 1 },
      { q: "A carbohydrate that consists of a single sugar unit and cannot be hydrolyzed into a simpler carbohydrate is classified as a:", options: ["Disaccharide", "Polysaccharide", "Monosaccharide", "Oligosaccharide"], correct: 2 },
      { q: "The formation of a glycosidic bond between two monosaccharide molecules involves:", options: ["Addition of water during the reaction", "Removal of a water molecule in a condensation reaction", "Breaking of peptide linkage", "Addition of oxygen without hydrogen removal"], correct: 1 },
      { q: "Starch and glycogen differ structurally mainly because glycogen:", options: ["Contains peptide linkages", "Is less branched than starch", "Is more highly branched than starch", "Contains nitrogen atoms"], correct: 2 },
      { q: "Cellulose is indigestible to humans because:", options: ["It contains α-1,4 glycosidic bonds", "It contains β-1,4 glycosidic bonds which humans cannot hydrolyze", "It is a lipid", "It lacks glucose units"], correct: 1 },
      { q: "A fatty acid that remains solid at room temperature and contains no carbon–carbon double bonds is most accurately described as:", options: ["Unsaturated fatty acid", "Essential fatty acid", "Saturated fatty acid", "Trans fatty acid"], correct: 2 },
      { q: "The amphipathic nature of phospholipids enables them to:", options: ["Dissolve completely in water", "Form micelles and lipid bilayers in aqueous environments", "Act as enzymes", "Store genetic information"], correct: 1 },
      { q: "In triglycerides, ester linkages are formed between:", options: ["Amino and carboxyl groups", "Phosphate and sugar groups", "Hydroxyl group of glycerol and carboxyl group of fatty acids", "Nitrogenous bases and sugars"], correct: 2 },
      { q: "Cholesterol is classified as a steroid because it:", options: ["Contains long chains of fatty acids", "Possesses four fused carbon rings", "Is composed of nucleotides", "Contains peptide bonds"], correct: 1 },
      { q: "The primary structure of a protein determines its overall shape because:", options: ["Peptide bonds are easily broken", "The sequence of amino acids dictates folding interactions", "It forms hydrogen bonds only", "It contains glycosidic linkages"], correct: 1 },
      { q: "Secondary protein structures such as α-helix and β-pleated sheet are stabilized mainly by:", options: ["Ionic bonds between R-groups", "Hydrogen bonds between backbone atoms", "Covalent disulfide bridges", "Phosphodiester bonds"], correct: 1 },
      { q: "Denaturation of a protein typically results in loss of biological activity because:", options: ["Amino acid sequence is destroyed", "Peptide bonds are hydrolyzed", "Three-dimensional conformation is altered", "DNA is mutated"], correct: 2 },
      { q: "A polypeptide exhibiting quaternary structure must:", options: ["Contain only one amino acid", "Be composed of more than one polypeptide chain", "Be hydrophobic", "Lack tertiary folding"], correct: 1 },
      { q: "The bond that links amino acids during protein synthesis is formed through:", options: ["Dehydration reaction between amino and carboxyl groups", "Hydrolysis of ATP", "Hydrogen bonding", "Ionic interaction"], correct: 0 },
      { q: "DNA differs structurally from RNA primarily because DNA:", options: ["Contains ribose sugar", "Contains uracil instead of thymine", "Is double stranded and contains deoxyribose", "Lacks nitrogenous bases"], correct: 2 },
      { q: "The complementary base pairing in DNA ensures accurate replication because adenine pairs with thymine through:", options: ["Three hydrogen bonds", "Two hydrogen bonds", "Covalent bonds", "Peptide bonds"], correct: 1 },
      { q: "ATP is considered the energy currency of the cell because:", options: ["It stores energy in glycosidic bonds", "It contains glucose", "Energy is released when terminal phosphate bond is hydrolyzed", "It is a lipid molecule"], correct: 2 },
      { q: "Hydrolysis reactions in biological systems generally:", options: ["Release water", "Consume water to break bonds", "Form peptide bonds", "Increase molecular size"], correct: 1 },
      { q: "The iodine test is used to detect starch because iodine:", options: ["Reacts with peptide bonds", "Binds within the helical structure of amylose", "Breaks glycosidic bonds", "Forms ester linkages"], correct: 1 },
      { q: "Benedict’s reagent produces a brick-red precipitate when heated with reducing sugars because:", options: ["Copper ions are reduced", "Peptide bonds are broken", "Lipids are oxidized", "Phosphate groups react"], correct: 0 },
      { q: "Water’s high specific heat capacity is biologically significant because it:", options: ["Evaporates rapidly", "Stabilizes internal temperature of organisms", "Is nonpolar", "Forms ionic bonds"], correct: 1 },
      { q: "The polarity of water molecules arises due to:", options: ["Equal sharing of electrons", "Unequal electronegativity between oxygen and hydrogen", "Presence of carbon", "Peptide linkage"], correct: 1 },
      { q: "Buffers in biological systems function primarily to:", options: ["Increase acidity", "Prevent drastic changes in pH", "Store energy", "Break hydrogen bonds"], correct: 1 },
      { q: "Essential amino acids must be obtained through diet because:", options: ["They contain sulfur", "The human body cannot synthesize them", "They are toxic", "They lack carboxyl groups"], correct: 1 },
      { q: "Polysaccharides serve structural roles in organisms primarily because:", options: ["They are hydrophobic", "They form long, repeating chains of monosaccharides", "They contain peptide bonds", "They are soluble in lipids"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 3: Enzymes",
    questions: [
      { q: "Enzymes are classified as biological catalysts because they:", options: ["Increase activation energy of reactions", "Decrease activation energy without being consumed", "Change equilibrium of reactions", "Become permanently altered"], correct: 1 },
      { q: "The three-dimensional structure of an enzyme is essential because:", options: ["It determines the active site configuration", "It increases temperature", "It stores ATP", "It alters substrate concentration"], correct: 0 },
      { q: "The active site of an enzyme is best described as:", options: ["A rigid groove permanently fixed", "A specific region where substrate binds temporarily", "A membrane structure", "A cytoplasmic vesicle"], correct: 1 },
      { q: "According to the lock and key model proposed by Emil Fischer, enzyme specificity is due to:", options: ["Flexible active site", "Exact structural complementarity", "ATP binding", "Temperature change"], correct: 1 },
      { q: "The induced-fit model suggests that:", options: ["Enzyme remains rigid", "Substrate changes permanently", "Active site adjusts shape upon substrate binding", "Enzyme is destroyed"], correct: 2 },
      { q: "The enzyme-substrate complex forms because of:", options: ["Covalent bonding permanently", "Temporary weak interactions", "DNA replication", "Ribosomal activity"], correct: 1 },
      { q: "Activation energy refers to:", options: ["Energy stored in ATP", "Minimum energy required to start a reaction", "Total heat produced", "Energy in products"], correct: 1 },
      { q: "Enzymes speed up reactions by:", options: ["Increasing product concentration", "Lowering activation energy barrier", "Increasing reactant mass", "Changing pH"], correct: 1 },
      { q: "Optimum temperature of human enzymes is approximately:", options: ["25°C", "37°C", "45°C", "60°C"], correct: 1 },
      { q: "Denaturation of enzymes results from:", options: ["Optimal pH", "Excessively high temperature altering structure", "Substrate deficiency", "Presence of water"], correct: 1 },
      { q: "pH affects enzyme activity primarily by:", options: ["Changing enzyme’s tertiary structure", "Increasing ATP", "Increasing substrate mass", "Breaking peptide bonds permanently"], correct: 0 },
      { q: "Competitive inhibitors reduce enzyme activity by:", options: ["Binding to allosteric site", "Competing with substrate for active site", "Destroying enzyme", "Increasing activation energy"], correct: 1 },
      { q: "Non-competitive inhibitors:", options: ["Bind only at active site", "Bind at different site altering enzyme shape", "Increase reaction rate", "Replace substrate"], correct: 1 },
      { q: "The term “cofactor” refers to:", options: ["Protein part of enzyme", "Non-protein helper molecule", "DNA segment", "Substrate"], correct: 1 },
      { q: "An organic cofactor is specifically called:", options: ["Prosthetic group", "Coenzyme", "Ribosome", "Lipase"], correct: 1 },
      { q: "Apoenzyme refers to:", options: ["Complete active enzyme", "Protein portion without cofactor", "Substrate", "Inhibitor"], correct: 1 },
      { q: "Holoenzyme is formed when:", options: ["Enzyme is denatured", "Apoenzyme binds cofactor", "Substrate leaves", "pH decreases"], correct: 1 },
      { q: "The rate of enzymatic reaction initially increases with substrate concentration because:", options: ["More active sites become occupied", "Enzyme concentration increases", "ATP increases", "Temperature rises"], correct: 0 },
      { q: "Reaction rate reaches maximum when:", options: ["Substrate is absent", "All active sites are saturated", "Enzyme is denatured", "pH is zero"], correct: 1 },
      { q: "Enzymes exhibit specificity mainly due to:", options: ["Random structure", "Unique active site configuration", "High temperature", "High pressure"], correct: 1 },
      { q: "Feedback inhibition is important because it:", options: ["Stops unnecessary product formation", "Increases ATP", "Destroys enzyme", "Increases activation energy"], correct: 0 },
      { q: "Reversible inhibition differs from irreversible inhibition because:", options: ["It permanently alters enzyme", "It can be reversed by removing inhibitor", "It denatures enzyme", "It forms covalent bond permanently"], correct: 1 },
      { q: "Enzyme activity generally doubles with a 10°C rise in temperature due to:", options: ["Reduced molecular motion", "Increased kinetic energy and collision frequency", "Decreased substrate", "DNA mutation"], correct: 1 },
      { q: "The graph of enzyme activity vs pH typically forms:", options: ["Straight line", "Bell-shaped curve", "Parabola opening upward", "Irregular pattern"], correct: 1 },
      { q: "Enzymes are highly efficient because they:", options: ["Are consumed in reactions", "Can be reused repeatedly", "Increase entropy", "Change equilibrium"], correct: 1 }
    ]
  }
];
