export const biologyClass10Quizzes = [
  {
    exercise: "Chapter 1: Gaseous Exchange",
    questions: [
      { q: "The process where C-H bonds in food are broken by oxidation-reduction reactions to generate ATP is called:", options: ["Breathing", "Gaseous exchange", "Cellular respiration", "Photosynthesis"], correct: 2 },
      { q: "In aerobic respiration, food material is completely oxidized using:", options: ["Carbon dioxide", "Nitrogen", "Oxygen", "Hydrogen"], correct: 2 },
      { q: "The physical process of taking in air to get oxygen and giving out air to remove carbon dioxide is:", options: ["Respiration", "Breathing", "Oxidation", "Deamination"], correct: 1 },
      { q: "Plants exchange gases with their environment through:", options: ["A specialized respiratory system", "Every cell of the plant body individually", "Only the roots", "Only the flowers"], correct: 1 },
      { q: "Microscopic pores in the epidermis of leaves for gaseous exchange are:", options: ["Lenticels", "Alveoli", "Stomata", "Bronchioles"], correct: 2 },
      { q: "During the daytime, mesophyll cells use the oxygen produced in photosynthesis for:", options: ["Transpiration", "Cellular respiration", "Storage", "Fermentation"], correct: 1 },
      { q: "At night, when photosynthesis stops, leaf cells:", options: ["Stop all gas exchange", "Take in oxygen and release carbon dioxide", "Take in carbon dioxide and release oxygen", "Perform photosynthesis using moonlight"], correct: 1 },
      { q: "Pores in the bark of woody stems and mature roots that allow air to pass are:", options: ["Stomata", "Lenticels", "Guard cells", "Cuticles"], correct: 1 },
      { q: "Aquatic plants obtain oxygen that is:", options: ["In gaseous form from the air", "Produced by fish", "Dissolved in water", "Taken from the soil"], correct: 2 },
      { q: "The gaseous exchange in young stems and leaves also occurs through the:", options: ["Bark", "Cuticle", "Phloem", "Xylem"], correct: 1 },
      { q: "The human respiratory system is divided into two main parts: the lungs and the:", options: ["Diaphragm", "Heart", "Air passageway", "Rib cage"], correct: 2 },
      { q: "The nasal cavity is divided into two portions by a:", options: ["Bone", "Wall", "Cartilage ring", "Muscle"], correct: 1 },
      { q: "The function of mucus and hair in the nasal cavity is to:", options: ["Produce sound", "Filter dust and moisten air", "Cool down the air", "Absorb oxygen"], correct: 1 },
      { q: "The common muscular passage for both food and air is the:", options: ["Larynx", "Pharynx", "Trachea", "Esophagus"], correct: 1 },
      { q: "The glottis is a narrow opening at the floor of the pharynx that leads to the:", options: ["Nasal cavity", "Larynx", "Bronchi", "Stomach"], correct: 1 },
      { q: "The flap of tissue that guards the glottis is the:", options: ["Vocal cord", "Soft palate", "Epiglottis", "Tonsil"], correct: 2 },
      { q: "The 'Voice Box' is another name for the:", options: ["Pharynx", "Larynx", "Trachea", "Bronchus"], correct: 1 },
      { q: "Sound is produced when air passes through and vibrates the:", options: ["Epiglottis", "Vocal cords", "Cartilage rings", "Alveoli"], correct: 1 },
      { q: "The trachea is also known as the:", options: ["Food pipe", "Windpipe", "Bronchial tree", "Pleural cavity"], correct: 1 },
      { q: "The length of the human trachea is approximately:", options: ["5 cm", "12 cm", "20 cm", "30 cm"], correct: 1 },
      { q: "The walls of the trachea contain C-shaped rings made of:", options: ["Bone", "Muscle", "Cartilage", "Fibrous tissue"], correct: 2 },
      { q: "The function of the cartilaginous rings in the trachea is to:", options: ["Produce mucus", "Prevent it from collapsing", "Help in swallowing", "Vibrate for speech"], correct: 1 },
      { q: "Upon entering the chest cavity, the trachea divides into two smaller tubes called:", options: ["Bronchioles", "Bronchi", "Alveolar ducts", "Capillaries"], correct: 1 },
      { q: "Fine tubes that lack cartilage and end in alveolar ducts are:", options: ["Bronchi", "Bronchioles", "Trachea", "Arterioles"], correct: 1 },
      { q: "The actual respiratory surface in the human body where gas exchange occurs is the:", options: ["Trachea", "Pharynx", "Alveoli", "Bronchi"], correct: 2 }
    ]
  },
  {
    exercise: "Chapter 2: Homeostasis",
    questions: [
      { q: "Homeostasis may be defined as the maintenance of the ______ conditions of the body at equilibrium.", options: ["External", "Internal", "Atmospheric", "Chemical"], correct: 1 },
      { q: "The maintenance of the amount of water and salts in body fluids is called:", options: ["Thermoregulation", "Excretion", "Osmoregulation", "Metabolism"], correct: 2 },
      { q: "Thermoregulation refers specifically to the maintenance of internal:", options: ["Glucose levels", "Water balance", "Temperature", "Blood pressure"], correct: 2 },
      { q: "The process by which metabolic wastes are eliminated from the body is:", options: ["Digestion", "Excretion", "Respiration", "Ingestion"], correct: 1 },
      { q: "Plants remove extra oxygen, which is a byproduct of ______, through their stomata.", options: ["Respiration", "Photosynthesis", "Transpiration", "Fermentation"], correct: 1 },
      { q: "At night, plants remove excess ______ because it is not being used for photosynthesis.", options: ["Oxygen", "Nitrogen", "Carbon dioxide", "Water"], correct: 2 },
      { q: "The removal of extra water from the plant body in the form of vapors is:", options: ["Guttation", "Transpiration", "Secretion", "Evaporation"], correct: 1 },
      { q: "The appearance of drops of water on the tips or edges of leaves through hydathodes is called:", options: ["Transpiration", "Guttation", "Condensation", "Osmosis"], correct: 1 },
      { q: "Plants that live in environments with an abundance of water are called:", options: ["Xerophytes", "Halophytes", "Hydrophytes", "Mesophytes"], correct: 2 },
      { q: "Xerophytes, like Cacti, adapt to dry environments by having:", options: ["Large leaves", "Deep roots and thick waxy cuticles", "No roots", "Sunken stomata on the upper surface"], correct: 1 },
      { q: "The primary organs involved in human homeostasis are the lungs, skin, and:", options: ["Heart", "Kidneys", "Stomach", "Brain"], correct: 1 },
      { q: "The lungs help maintain homeostasis by regulating the concentration of ______ in the blood.", options: ["Oxygen", "Carbon dioxide", "Nitrogen", "Glucose"], correct: 1 },
      { q: "The skin plays a major role in ______ and the removal of excess water and salts.", options: ["Digestion", "Thermoregulation", "Vision", "Hearing"], correct: 1 },
      { q: "The outer protective layer of the human skin is the:", options: ["Dermis", "Epidermis", "Hypodermis", "Subcutaneous layer"], correct: 1 },
      { q: "The inner layer of skin containing blood vessels, sensory nerve endings, and sweat glands is the:", options: ["Epidermis", "Dermis", "Cuticle", "Cortex"], correct: 1 },
      { q: "Sweat glands help cool the body through the process of:", options: ["Conduction", "Radiation", "Evaporation", "Insulation"], correct: 2 },
      { q: "The layer of ______ cells in the dermis provides insulation against heat loss.", options: ["Nerve", "Muscle", "Fat", "Epithelial"], correct: 2 },
      { q: "Goosebumps are caused by the contraction of small muscles attached to:", options: ["Sweat glands", "Hairs", "Blood vessels", "Bones"], correct: 1 },
      { q: "Skin also functions as a sensory organ to detect:", options: ["Light", "Sound", "Touch, pain, and pressure", "Smells"], correct: 2 },
      { q: "Excessive sweating without water replacement can lead to:", options: ["Hypertension", "Dehydration", "Diabetes", "Obesity"], correct: 1 },
      { q: "The human excretory system is also known as the:", options: ["Digestive system", "Urinary system", "Circulatory system", "Nervous system"], correct: 1 },
      { q: "Humans have a pair of ______-shaped kidneys.", options: ["Oval", "Bean", "Round", "Heart"], correct: 1 },
      { q: "The tube that carries urine from the kidney to the urinary bladder is the:", options: ["Urethra", "Ureter", "Vas deferens", "Fallopian tube"], correct: 1 },
      { q: "Urine leaves the body through a tube called the:", options: ["Ureter", "Urethra", "Collecting duct", "Renal pelvis"], correct: 1 },
      { q: "The functional unit of the kidney is the:", options: ["Neuron", "Nephron", "Alveolus", "Villus"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 3: Coordination and Control",
    questions: [
      { q: "Which type of coordination in humans involves the nervous system?", options: ["Chemical coordination", "Nervous coordination", "Mechanical coordination", "Thermal coordination"], correct: 1 },
      { q: "Chemical coordination in the human body is achieved through the:", options: ["Brain", "Endocrine system", "Spinal cord", "Muscles"], correct: 1 },
      { q: "Any change in the environment (internal or external) that can evoke a response is a:", options: ["Response", "Stimulus", "Receptor", "Effector"], correct: 1 },
      { q: "Organs, tissues, or cells which are specialized to detect stimuli are called:", options: ["Effectors", "Receptors", "Coordinators", "Neurons"], correct: 1 },
      { q: "In nervous coordination, the ______ and ______ act as coordinators.", options: ["Muscles; Glands", "Brain; Spinal cord", "Heart; Lungs", "Liver; Pancreas"], correct: 1 },
      { q: "The parts of the body that receive messages from coordinators and produce particular responses are:", options: ["Receptors", "Effectors", "Stimuli", "Neurons"], correct: 1 },
      { q: "In chemical coordination, coordinators are the:", options: ["Brain cells", "Endocrine glands", "Nerves", "Skin cells"], correct: 1 },
      { q: "The action performed by an effector in result of a stimulus is the:", options: ["Impulse", "Response", "Coordination", "Secretion"], correct: 1 },
      { q: "Which coordination produces immediate but short-living responses?", options: ["Chemical coordination", "Nervous coordination", "Plant coordination", "Both a and b"], correct: 1 },
      { q: "The responses in chemical coordination are generally ______ but ______.", options: ["Fast; Short-living", "Slow; Long-lasting", "Immediate; Short-living", "Fast; Long-lasting"], correct: 1 },
      { q: "The central nervous system (CNS) consists of the ______ and ______.", options: ["Cranial nerves; Spinal nerves", "Brain; Spinal cord", "Neurons; Ganglia", "Receptors; Effectors"], correct: 1 },
      { q: "The basic structural and functional unit of the nervous system is the:", options: ["Nephron", "Neuron (nerve cell)", "Alveolus", "Glial cell"], correct: 1 },
      { q: "Which part of the neuron contains the nucleus and most of the cytoplasm?", options: ["Axon", "Dendrite", "Cell body", "Myelin sheath"], correct: 2 },
      { q: "The cytoplasmic projections that carry impulses toward the cell body are:", options: ["Axons", "Dendrites", "Nodes of Ranvier", "Schwann cells"], correct: 1 },
      { q: "The projection that carries impulses away from the cell body is the:", options: ["Dendrite", "Axon", "Synapse", "Myelin"], correct: 1 },
      { q: "Schwann cells wrap around axons to form a fatty layer called the:", options: ["Cytoplasm", "Myelin sheath", "Node of Ranvier", "Ganglion"], correct: 1 },
      { q: "The gaps between myelin sheath segments on an axon are called:", options: ["Synapses", "Nodes of Ranvier", "Dendrites", "Reflex arcs"], correct: 1 },
      { q: "Neurons that carry information from receptors to the CNS are:", options: ["Motor neurons", "Sensory neurons", "Interneurons", "Effector neurons"], correct: 1 },
      { q: "Neurons found only in the CNS that integrate information are:", options: ["Sensory neurons", "Motor neurons", "Interneurons", "Cranial neurons"], correct: 2 },
      { q: "A 'nerve' is a bundle of ______ enveloped by a common sheath.", options: ["Cell bodies", "Axons", "Dendrites", "Interneurons"], correct: 1 },
      { q: "The brain is protected by a bony structure called the:", options: ["Vertebral column", "Cranium (part of the skull)", "Rib cage", "Sternum"], correct: 1 },
      { q: "The three layers of membranes that protect the brain are the:", options: ["Pleural membranes", "Meninges", "Pericardium", "Peritoneum"], correct: 1 },
      { q: "Fluid found in the ventricles of the brain and central canal of the spinal cord is:", options: ["Blood", "Lymph", "Cerebrospinal fluid (CSF)", "Mucus"], correct: 2 },
      { q: "The largest part of the human brain is the:", options: ["Cerebellum", "Cerebrum", "Medulla oblongata", "Midbrain"], correct: 1 },
      { q: "The 'Thalamus' serves as a relay center for ______ information.", options: ["Motor", "Sensory", "Reflexive", "Digestive"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 4: Support and Movement",
    questions: [
      { q: "The human skeleton is primarily divided into two main parts: the axial skeleton and the:", options: ["Central skeleton", "Appendicular skeleton", "Peripheral skeleton", "Internal skeleton"], correct: 1 },
      { q: "How many bones are present in the adult human body?", options: ["200", "206", "212", "300"], correct: 1 },
      { q: "The axial skeleton consists of how many bones?", options: ["60", "80", "120", "126"], correct: 1 },
      { q: "The skull is composed of cranial bones and ______ bones.", options: ["Facial", "Auditory", "Spinal", "Rib"], correct: 0 },
      { q: "How many bones make up the human cranium?", options: ["6", "8", "10", "14"], correct: 1 },
      { q: "The vertebral column (backbone) is made up of a series of bones called:", options: ["Carpals", "Vertices", "Vertebrae", "Tarsals"], correct: 2 },
      { q: "There are ______ pairs of ribs in the human chest cavity.", options: ["10", "12", "24", "31"], correct: 1 },
      { q: "The bone in the center of the chest to which most ribs are attached is the:", options: ["Clavicle", "Sternum (breastbone)", "Scapula", "Humerus"], correct: 1 },
      { q: "The appendicular skeleton consists of a total of ______ bones.", options: ["80", "126", "206", "64"], correct: 1 },
      { q: "The pectoral girdle connects the ______ to the axial skeleton.", options: ["Arms", "Legs", "Pelvis", "Skull"], correct: 0 },
      { q: "The dense, hard outer layer of a bone is called:", options: ["Spongy bone", "Compact bone", "Bone marrow", "Periosteum"], correct: 1 },
      { q: "The interior of many bones contains ______, where blood cells are produced.", options: ["Cartilage", "Yellow marrow", "Red bone marrow", "Calcium"], correct: 2 },
      { q: "Bone-forming cells are known as:", options: ["Osteoclasts", "Osteoblasts", "Chondrocytes", "Neurons"], correct: 1 },
      { q: "Mature bone cells are called:", options: ["Osteocytes", "Leukocytes", "Myocytes", "Fibroblasts"], correct: 0 },
      { q: "Cartilage is a type of connective tissue that is ______ than bone.", options: ["Harder", "Softer and more flexible", "More brittle", "Heavier"], correct: 1 },
      { q: "The cells found in cartilage are called:", options: ["Osteocytes", "Chondrocytes", "Platelets", "Alveoli"], correct: 1 },
      { q: "Which type of cartilage is found at the ends of long bones and in the nose?", options: ["Elastic cartilage", "Fibrocartilage", "Hyaline cartilage", "Calcified cartilage"], correct: 2 },
      { q: "The type of cartilage found in the external ear (pinna) and epiglottis is:", options: ["Hyaline", "Elastic", "Fibrous", "Spongy"], correct: 1 },
      { q: "Ligaments are tough bands of connective tissue that join:", options: ["Muscle to bone", "Bone to bone", "Muscle to muscle", "Nerve to muscle"], correct: 1 },
      { q: "Tendons are connective tissues that attach:", options: ["Bone to bone", "Muscle to bone", "Skin to muscle", "Ribs to sternum"], correct: 1 },
      { q: "A location where two or more bones meet is called a:", options: ["Ligament", "Joint", "Tendon", "Suture"], correct: 1 },
      { q: "Joints that allow no movement, such as those in the skull, are:", options: ["Slightly movable joints", "Immovable (fixed) joints", "Freely movable joints", "Hinge joints"], correct: 1 },
      { q: "The joints between vertebrae are examples of:", options: ["Fixed joints", "Slightly movable joints", "Ball and socket joints", "Gliding joints"], correct: 1 },
      { q: "Which type of joint allows movement in all directions?", options: ["Hinge joint", "Ball and socket joint", "Fixed joint", "Pivot joint"], correct: 1 },
      { q: "The shoulder and hip joints are examples of ______ joints.", options: ["Hinge", "Ball and socket", "Gliding", "Suture"], correct: 1 }
    ]
  }
];
