export const biologyClass9Quizzes = [
  {
    exercise: "Chapter 1: Introduction to Biology",
    questions: [
      { q: "Biology is best defined as the study of:", options: ["Plants only", "Living organisms and their interactions", "Human anatomy", "Chemical reactions in organisms"], correct: 1 },
      { q: "Which of the following is NOT a branch of biology but an interdisciplinary field?", options: ["Biochemistry", "Zoology", "Botany", "Microbiology"], correct: 0 },
      { q: "The study of structure at microscopic level is:", options: ["Anatomy", "Histology", "Morphology", "Physiology"], correct: 1 },
      { q: "Which branch deals with classification of organisms?", options: ["Taxonomy", "Ecology", "Genetics", "Embryology"], correct: 0 },
      { q: "A biologist studying internal functions of liver is working in:", options: ["Anatomy", "Physiology", "Histology", "Taxonomy"], correct: 1 },
      { q: "A scientist studies how deforestation affects animal populations. This is:", options: ["Physiology", "Ecology", "Taxonomy", "Morphology"], correct: 1 },
      { q: "If a disease spreads due to microbial imbalance, which field is most relevant?", options: ["Botany", "Microbiology", "Zoology", "Anatomy"], correct: 1 },
      { q: "Observing behavior of animals in natural habitat relates to:", options: ["Ethology", "Ecology", "Genetics", "Taxonomy"], correct: 0 },
      { q: "Studying DNA mutations requires knowledge of:", options: ["Anatomy", "Genetics", "Ecology", "Physiology"], correct: 1 },
      { q: "A student compares bone structures of mammals. This relates to:", options: ["Physiology", "Comparative anatomy", "Histology", "Biochemistry"], correct: 1 },
      { q: "Which statement best explains why biology is linked with chemistry?", options: ["Living organisms contain chemicals", "All reactions in life are chemical", "Chemical processes govern life functions", "Biology is a branch of chemistry"], correct: 2 },
      { q: "Why is biology linked with physics?", options: ["Organisms obey physical laws", "Biology studies energy transformations", "Instruments use physics principles", "All of the above"], correct: 3 },
      { q: "Which is the MOST appropriate reason biology is called a natural science?", options: ["It studies living organisms", "It uses experiments", "It deals with natural phenomena", "It explains chemical reactions"], correct: 2 },
      { q: "If biology did not integrate with mathematics, what would be MOST affected?", options: ["Classification", "Data analysis and statistics", "Cell structure", "Photosynthesis"], correct: 1 },
      { q: "Which scenario best shows applied biology?", options: ["Studying cell structure", "Developing vaccines", "Observing plants", "Learning classification"], correct: 1 },
      { q: "A doctor uses knowledge of biology to treat disease. This is:", options: ["Basic biology", "Applied biology", "Theoretical biology", "Experimental biology"], correct: 1 },
      { q: "A farmer increases crop yield using fertilizers. This relates to:", options: ["Genetics", "Agriculture biology", "Zoology", "Anatomy"], correct: 1 },
      { q: "If a scientist develops antibiotics, it involves:", options: ["Botany", "Microbiology", "Anatomy", "Ecology"], correct: 1 },
      { q: "Environmental pollution study belongs to:", options: ["Physiology", "Ecology", "Taxonomy", "Histology"], correct: 1 },
      { q: "Studying fossil records relates to:", options: ["Paleontology", "Embryology", "Genetics", "Histology"], correct: 0 },
      { q: "Assertion: Biology helps improve quality of life. Reason: It provides solutions to health problems.", options: ["Both correct, reason explains assertion", "Both correct, but unrelated", "Assertion correct, reason wrong", "Both wrong"], correct: 0 },
      { q: "Assertion: All branches of biology are independent. Reason: They study different aspects of life.", options: ["Both correct", "Both wrong", "Assertion wrong, reason correct", "Both correct but not explanation"], correct: 2 },
      { q: "Assertion: Biotechnology is applied biology. Reason: It uses living organisms for human benefit.", options: ["Both correct, reason explains", "Both correct, not explanation", "Assertion wrong", "Reason wrong"], correct: 0 },
      { q: "Which field is MOST dependent on genetics?", options: ["Ecology", "Biotechnology", "Anatomy", "Morphology"], correct: 1 },
      { q: "Which is NOT directly related to biology?", options: ["Physics", "Chemistry", "Astronomy", "Mathematics"], correct: 2 }
    ]
  },
  {
    exercise: "Chapter 2: Solving a Biological Problem",
    questions: [
      { q: "Biological method is primarily used to:", options: ["Memorize facts", "Solve biological problems systematically", "Classify organisms", "Study fossils"], correct: 1 },
      { q: "The first step in biological method is:", options: ["Experimentation", "Hypothesis", "Observation", "Conclusion"], correct: 2 },
      { q: "A hypothesis must be:", options: ["Always correct", "Testable", "Based on guess only", "Complex"], correct: 1 },
      { q: "Deduction in biological method involves:", options: ["Guessing outcome", "Predicting results from hypothesis", "Observing data", "Recording results"], correct: 1 },
      { q: "Which step verifies a hypothesis?", options: ["Observation", "Experimentation", "Deduction", "Conclusion"], correct: 1 },
      { q: "A scientist observes plants growing faster in sunlight. This is:", options: ["Hypothesis", "Observation", "Experiment", "Deduction"], correct: 1 },
      { q: "Predicting “plants need sunlight for growth” is:", options: ["Observation", "Hypothesis", "Deduction", "Conclusion"], correct: 1 },
      { q: "Testing plant growth with and without sunlight is:", options: ["Observation", "Hypothesis", "Experimentation", "Deduction"], correct: 2 },
      { q: "A doctor tests a new drug on patients. This is:", options: ["Observation", "Experimentation", "Deduction", "Conclusion"], correct: 1 },
      { q: "Which step involves analyzing collected data?", options: ["Observation", "Conclusion", "Hypothesis", "Deduction"], correct: 1 },
      { q: "Why must a hypothesis be testable?", options: ["To make it complex", "To verify scientifically", "To avoid experiments", "To make it theoretical"], correct: 1 },
      { q: "If results contradict hypothesis, scientist should:", options: ["Ignore results", "Change hypothesis", "Stop experiment", "Memorize data"], correct: 1 },
      { q: "Which is MOST important in experimentation?", options: ["Guessing", "Controlled variables", "Writing notes", "Classification"], correct: 1 },
      { q: "Which variable is deliberately changed?", options: ["Controlled", "Dependent", "Independent", "Constant"], correct: 2 },
      { q: "Which variable is measured as result?", options: ["Independent", "Dependent", "Controlled", "Constant"], correct: 1 },
      { q: "A student tests the effect of fertilizer on plant growth. Fertilizer is:", options: ["Dependent variable", "Independent variable", "Controlled variable", "Constant"], correct: 1 },
      { q: "Plant height measured is:", options: ["Independent", "Dependent", "Controlled", "Constant"], correct: 1 },
      { q: "Keeping water same in all plants ensures:", options: ["Bias", "Control", "Hypothesis", "Deduction"], correct: 1 },
      { q: "If experiment repeated multiple times, it ensures:", options: ["Accuracy", "Bias", "Error", "Guess"], correct: 0 },
      { q: "A scientist concludes after an experiment. This is:", options: ["Observation", "Deduction", "Conclusion", "Hypothesis"], correct: 2 },
      { q: "Data collected during experiment is called:", options: ["Observation", "Evidence", "Conclusion", "Theory"], correct: 1 },
      { q: "Quantitative data refers to:", options: ["Descriptions", "Numbers", "Ideas", "Hypothesis"], correct: 1 },
      { q: "Qualitative data refers to:", options: ["Numbers", "Measurements", "Descriptions", "Graphs"], correct: 2 },
      { q: "Which improves reliability?", options: ["Single test", "Repeated trials", "Guess", "Assumption"], correct: 1 },
      { q: "Graphs are used to:", options: ["Decorate", "Analyze data", "Memorize", "Observe"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 3: Biodiversity",
    questions: [
      { q: "Biodiversity refers to:", options: ["Only plants", "Variety of living organisms", "Only animals", "Ecosystem only"], correct: 1 },
      { q: "Classification mainly helps to:", options: ["Memorize organisms", "Study relationships", "Name organisms only", "Study cells"], correct: 1 },
      { q: "The main basis of modern classification is:", options: ["Size", "Morphology", "Evolutionary relationships", "Habitat"], correct: 2 },
      { q: "Aristotle classified organisms based on:", options: ["DNA", "Habitat", "Morphology", "Evolution"], correct: 1 },
      { q: "Which kingdom includes prokaryotes?", options: ["Protista", "Monera", "Fungi", "Plantae"], correct: 1 },
      { q: "Which is the MOST advanced classification system?", options: ["Two-kingdom", "Three-kingdom", "Five-kingdom", "Artificial"], correct: 2 },
      { q: "Which characteristic distinguishes prokaryotes?", options: ["Nucleus present", "Membrane-bound organelles", "No true nucleus", "Multicellular"], correct: 2 },
      { q: "Which kingdom includes unicellular eukaryotes?", options: ["Monera", "Protista", "Fungi", "Plantae"], correct: 1 },
      { q: "Fungi differ from plants because they:", options: ["Are multicellular", "Are autotrophic", "Lack chlorophyll", "Have cell walls"], correct: 2 },
      { q: "Which kingdom shows the highest diversity?", options: ["Monera", "Protista", "Animalia", "Fungi"], correct: 2 },
      { q: "An organism without nucleus but having cell wall belongs to:", options: ["Protista", "Monera", "Fungi", "Plantae"], correct: 1 },
      { q: "A unicellular organism with nucleus is classified in:", options: ["Monera", "Protista", "Fungi", "Plantae"], correct: 1 },
      { q: "Mushroom belongs to:", options: ["Plantae", "Animalia", "Fungi", "Protista"], correct: 2 },
      { q: "An organism that performs photosynthesis but is unicellular belongs to:", options: ["Protista", "Monera", "Fungi", "Animalia"], correct: 0 },
      { q: "Bacteria causing disease belong to:", options: ["Protista", "Monera", "Fungi", "Animalia"], correct: 1 },
      { q: "Why is five-kingdom classification preferred?", options: ["Simplicity", "Based on evolutionary relationships", "Based on size", "Based on habitat"], correct: 1 },
      { q: "Which feature is MOST reliable for classification?", options: ["Color", "Shape", "Genetic similarity", "Size"], correct: 2 },
      { q: "Which kingdom includes both autotrophs and heterotrophs?", options: ["Monera", "Protista", "Fungi", "Animalia"], correct: 1 },
      { q: "Which group lacks a cell wall?", options: ["Plants", "Fungi", "Animals", "Bacteria"], correct: 2 },
      { q: "Which kingdom includes decomposers?", options: ["Animalia", "Plantae", "Fungi", "Protista"], correct: 2 },
      { q: "Scientific naming system is called:", options: ["Classification", "Taxonomy", "Binomial nomenclature", "Identification"], correct: 2 },
      { q: "Who introduced binomial nomenclature?", options: ["Aristotle", "Linnaeus", "Darwin", "Pasteur"], correct: 1 },
      { q: "Scientific name has:", options: ["One word", "Two words", "Three words", "Four words"], correct: 1 },
      { q: "First word represents:", options: ["Species", "Genus", "Family", "Order"], correct: 1 },
      { q: "Second word represents:", options: ["Species", "Genus", "Kingdom", "Class"], correct: 0 }
    ]
  },
  {
    exercise: "Chapter 4: Cell Structure & Function",
    questions: [
      { q: "The basic unit of life is:", options: ["Atom", "Cell", "Tissue", "Organ"], correct: 1 },
      { q: "Which is the smallest living structure?", options: ["Atom", "Molecule", "Cell", "Organ"], correct: 2 },
      { q: "All living organisms are composed of:", options: ["Atoms", "Cells", "Organs", "Tissues"], correct: 1 },
      { q: "Cell theory was proposed by:", options: ["Hooke", "Schleiden and Schwann", "Virchow", "Darwin"], correct: 1 },
      { q: "Which statement is NOT part of cell theory?", options: ["All cells arise from pre‑existing cells", "Cells are unit of life", "All organisms are multicellular", "Cells are basic structural units"], correct: 2 },
      { q: "Which organelle is known as a protein factory?", options: ["Lysosome", "Ribosome", "Mitochondria", "Chloroplast"], correct: 1 },
      { q: "The control center of a cell is:", options: ["Nucleus", "Mitochondria", "Ribosome", "Golgi"], correct: 0 },
      { q: "Which organelle produces energy (ATP)?", options: ["Nucleus", "Mitochondria", "Ribosome", "ER"], correct: 1 },
      { q: "Cell wall is present in:", options: ["Animal cells", "Plant cells", "Both", "Only bacteria"], correct: 1 },
      { q: "Which is the site of photosynthesis?", options: ["Mitochondria", "Chloroplast", "Ribosome", "Nucleus"], correct: 1 },
      { q: "Cell membrane is composed mainly of:", options: ["Carbohydrate", "Protein & lipid", "Nucleic acid", "Vitamins"], correct: 1 },
      { q: "Which transport process does NOT require energy?", options: ["Endocytosis", "Exocytosis", "Diffusion", "Active transport"], correct: 2 },
      { q: "Movement of water across membrane is called:", options: ["Diffusion", "Osmosis", "Active transport", "Endocytosis"], correct: 1 },
      { q: "Which requires energy?", options: ["Diffusion", "Osmosis", "Active transport", "Facilitated diffusion"], correct: 2 },
      { q: "Facilitated diffusion occurs through:", options: ["Channels", "Vesicles", "Cytoplasm", "Cell wall"], correct: 0 },
      { q: "Which is present only in plant cells?", options: ["Centriole", "Chloroplast", "Lysosome", "Flagella"], correct: 1 },
      { q: "Which is present only in animal cells?", options: ["Cell wall", "Central vacuole", "Centriole", "Chloroplast"], correct: 2 },
      { q: "Which structure packages proteins?", options: ["ER", "Nucleus", "Golgi apparatus", "Lysosome"], correct: 2 },
      { q: "Lysosomes function mainly in:", options: ["ATP production", "Digestion of materials", "Protein synthesis", "Photosynthesis"], correct: 1 },
      { q: "ER stands for:", options: ["Endoplasmic reticulum", "Endo ribozyme", "Extra reticulum", "Extra ribosome"], correct: 0 },
      { q: "A cell without mitochondria cannot:", options: ["Synthesize protein", "Produce ATP efficiently", "Store water", "Control activities"], correct: 1 },
      { q: "Which cell feature would most directly affect the rate of diffusion in cells?", options: ["Cell size", "Nucleus", "ER", "Golgi"], correct: 0 },
      { q: "Red blood cells take in oxygen by:", options: ["Active transport", "Osmosis", "Diffusion", "Endocytosis"], correct: 2 },
      { q: "Which cell type has more mitochondria?", options: ["Muscle cells", "Fat cells", "Skin cells", "Bone cells"], correct: 0 },
      { q: "The presence of many ribosomes indicates high rate of:", options: ["Respiration", "Protein synthesis", "Photosynthesis", "Digestion"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 5: Human Nutrition",
    questions: [
      { q: "Nutrition is the process of:", options: ["Producing food", "Consuming and using food", "Breaking bones", "Excreting urine"], correct: 1 },
      { q: "A balanced diet must include:", options: ["Only carbohydrates", "Carbohydrates, proteins, fats, vitamins, minerals & water", "Only proteins", "Only vitamins"], correct: 1 },
      { q: "The main energy-yielding nutrient is:", options: ["Protein", "Carbohydrate", "Minerals", "Vitamins"], correct: 1 },
      { q: "Which nutrient repairs body tissues?", options: ["Protein", "Fat", "Fiber", "Water"], correct: 0 },
      { q: "Which vitamin is fat-soluble?", options: ["Vitamin C", "Vitamin B", "Vitamin A", "Vitamin B12"], correct: 2 },
      { q: "Deficiency of vitamin D causes:", options: ["Scurvy", "Rickets", "Anemia", "Night blindness"], correct: 1 },
      { q: "Lack of iron causes:", options: ["Goitre", "Anemia", "Rickets", "Obesity"], correct: 1 },
      { q: "Vitamin C mainly prevents:", options: ["Rickets", "Scurvy", "Beriberi", "Night blindness"], correct: 1 },
      { q: "Major function of fats is:", options: ["Build muscles", "Provide energy and insulation", "Carry oxygen", "Process waste"], correct: 1 },
      { q: "Dietary fiber is important for:", options: ["Energy only", "Smooth digestion & bowel movement", "Muscle building", "Bone strength"], correct: 1 },
      { q: "Which organ begins the digestive process?", options: ["Stomach", "Small intestine", "Mouth", "Colon"], correct: 2 },
      { q: "The enzyme amylase is secreted by:", options: ["Stomach", "Salivary glands", "Liver", "Pancreas"], correct: 1 },
      { q: "Protein digestion begins in:", options: ["Mouth", "Stomach", "Small intestine", "Esophagus"], correct: 1 },
      { q: "Bile helps in:", options: ["Protein digestion", "Fat emulsification", "Carbohydrate digestion", "Absorption of water"], correct: 1 },
      { q: "Which part absorbs most nutrients?", options: ["Stomach", "Large intestine", "Small intestine", "Mouth"], correct: 2 },
      { q: "A patient with jaundice has damaged:", options: ["Stomach", "Liver", "Pancreas", "Kidney"], correct: 1 },
      { q: "If villi are destroyed in the intestine, absorption will:", options: ["Increase", "Decrease significantly", "Remain same", "Only fats absorbed"], correct: 1 },
      { q: "Excess fat in diet may lead to:", options: ["Malnutrition", "Obesity", "Anemia", "Scurvy"], correct: 1 },
      { q: "Sugar rush after eating sweets is due to:", options: ["Slow digestion", "Rapid absorption of glucose", "Protein breakdown", "Fat emulsification"], correct: 1 },
      { q: "A person with lack of saliva would have difficulty starting:", options: ["Protein digestion", "Carbohydrate digestion", "Fat digestion", "Water absorption"], correct: 1 },
      { q: "Why does fatty food take longer to digest?", options: ["Requires greater emulsification", "Contains no nutrients", "Is water soluble", "Does not enter intestine"], correct: 0 },
      { q: "Which condition would impair digestion the most?", options: ["Lack of water", "Deficiency of digestive enzymes", "Lack of exercise", "Lack of sunlight"], correct: 1 },
      { q: "An enzyme acts as:", options: ["Structural unit", "Biological catalyst", "Source of energy", "Immunity booster"], correct: 1 },
      { q: "Which would result if bile is not released?", options: ["Protein digestion fails", "Fat digestion decreases", "Carbohydrate digestion increases", "Water absorption fails"], correct: 1 },
      { q: "If small intestine motility decreases, nutrient absorption:", options: ["Increases", "Decreases", "Remains same", "Stops completely"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 6: Life Processes",
    questions: [
      { q: "Life processes are essential for:", options: ["Growth", "Survival", "Reproduction", "All of the above"], correct: 3 },
      { q: "Which is NOT a life process?", options: ["Respiration", "Nutrition", "Photosynthesis", "Excretion"], correct: 2 },
      { q: "Nutrition supplies the body with:", options: ["Hormones", "Nutrients & energy", "Nerve signals", "Immune cells"], correct: 1 },
      { q: "Respiration primarily releases:", options: ["Nutrients", "Energy", "Heat only", "Water"], correct: 1 },
      { q: "Excretion removes:", options: ["Food", "Waste products", "Oxygen", "Hormones"], correct: 1 },
      { q: "Which organism is autotrophic?", options: ["Human", "Snake", "Green plant", "Fungi"], correct: 2 },
      { q: "Heterotrophs obtain nutrients by:", options: ["Photosynthesis", "Eating other organisms", "Self‑synthesis", "Chemical synthesis"], correct: 1 },
      { q: "Saprophytes feed on:", options: ["Live tissues", "Dead organic matter", "Minerals in soil", "Water only"], correct: 1 },
      { q: "Which is a heterotrophic human organ?", options: ["Stomach", "Lungs", "Heart", "Skin"], correct: 0 },
      { q: "In human nutrition, digestion starts in:", options: ["Stomach", "Mouth", "Small intestine", "Esophagus"], correct: 1 },
      { q: "Which gas is taken in for respiration?", options: ["CO₂", "O₂", "N₂", "H₂"], correct: 1 },
      { q: "The site of gaseous exchange in humans is:", options: ["Trachea", "Bronchi", "Alveoli", "Nasal cavity"], correct: 2 },
      { q: "Breathing rate increases during:", options: ["Sleep", "Exercise", "Rest", "Starvation"], correct: 1 },
      { q: "Internal respiration occurs in:", options: ["Blood capillaries & tissues", "Lungs only", "Trachea", "Bronchioles"], correct: 0 },
      { q: "Which structure prevents food entering the windpipe?", options: ["Larynx", "Epiglottis", "Pharynx", "Trachea"], correct: 1 },
      { q: "Blood is circulated by the:", options: ["Brain", "Liver", "Heart", "Kidney"], correct: 2 },
      { q: "Which chamber receives oxygenated blood from lungs?", options: ["Right atrium", "Left atrium", "Right ventricle", "Left ventricle"], correct: 1 },
      { q: "Which vessel carries blood away from the heart?", options: ["Vein", "Artery", "Capillary", "Lymph"], correct: 1 },
      { q: "Deoxygenated blood reaches the heart via:", options: ["Pulmonary vein", "Aorta", "Vena cava", "Pulmonary artery"], correct: 2 },
      { q: "Valves in heart prevent:", options: ["Blood clotting", "Backflow of blood", "Oxygen exchange", "Pulse"], correct: 1 },
      { q: "Which organ removes nitrogenous wastes?", options: ["Heart", "Kidney", "Lungs", "Skin"], correct: 1 },
      { q: "Filtration of blood occurs in the:", options: ["Bowman’s capsule", "Renal artery", "Ureter", "Bladder"], correct: 0 },
      { q: "Urine is temporarily stored in:", options: ["Ureter", "Bladder", "Urethra", "Nephron"], correct: 1 },
      { q: "The functional unit of kidney is:", options: ["Ureter", "Nephron", "Bladder", "Cortex"], correct: 1 },
      { q: "Which is NOT a waste product?", options: ["Urea", "CO₂", "Oxygen", "Uric acid"], correct: 2 }
    ]
  },
  {
    exercise: "Chapter 7: Transport in Plants & Animals",
    questions: [
      { q: "Transport in living organisms refers to movement of:", options: ["Nutrients only", "Nutrients, gases, and waste products", "Water only", "Cells only"], correct: 1 },
      { q: "Xylem mainly transports:", options: ["Sugars", "Water & minerals", "Oxygen", "Hormones"], correct: 1 },
      { q: "Phloem mainly transports:", options: ["Water", "Minerals", "Sugars", "Gases"], correct: 2 },
      { q: "In animals, blood primarily transports:", options: ["Digested food, gases, wastes", "Water only", "Proteins only", "Vitamins only"], correct: 0 },
      { q: "Which cell helps water absorption in roots?", options: ["Guard cells", "Root hair cells", "Xylem", "Phloem"], correct: 1 },
      { q: "Transpiration pull is caused by:", options: ["Root pressure", "Water evaporation from leaves", "Photosynthesis", "Gravity"], correct: 1 },
      { q: "Water moves up a plant mainly due to:", options: ["Active transport", "Transpiration pull", "Gravity", "Soil pressure"], correct: 1 },
      { q: "Which process moves water from soil to roots?", options: ["Transpiration", "Osmosis", "Evaporation", "Diffusion"], correct: 1 },
      { q: "Casparian strip forces water to pass through:", options: ["Cell wall", "Cell membrane", "Xylem directly", "Stomata"], correct: 1 },
      { q: "Root pressure develops mainly because of:", options: ["Heat", "Water uptake by roots", "Photosynthesis", "Gaseous exchange"], correct: 1 },
      { q: "The fluid connective tissue in humans is:", options: ["Lymph", "Plasma", "Blood", "Tissue fluid"], correct: 2 },
      { q: "Red blood cells carry:", options: ["CO₂", "O₂", "Hormones", "Enzymes"], correct: 1 },
      { q: "White blood cells function in:", options: ["Transporting oxygen", "Immunity", "Digestion", "Excretion"], correct: 1 },
      { q: "Platelets are important for:", options: ["Breathing", "Clotting", "Breathing", "Absorption"], correct: 1 },
      { q: "Plasma is mainly composed of:", options: ["Water", "Proteins", "Cells", "Hormones"], correct: 0 },
      { q: "The heart in humans has:", options: ["Two chambers", "Three chambers", "Four chambers", "Five chambers"], correct: 2 },
      { q: "Which carries oxygenated blood to body tissues?", options: ["Pulmonary vein", "Pulmonary artery", "Aorta", "Vena cava"], correct: 2 },
      { q: "Which vessel carries blood back to the heart?", options: ["Artery", "Vein", "Capillary", "Xylem"], correct: 1 },
      { q: "Capillaries are important for:", options: ["Rapid heartbeat", "Exchange of materials", "Nutrient storage", "Bone growth"], correct: 1 },
      { q: "Which valve prevents backflow into the left atrium?", options: ["Tricuspid", "Bicuspid (mitral)", "Pulmonary", "Aortic"], correct: 1 },
      { q: "Root pressure is most important when:", options: ["Transpiration is high", "At night", "During exercise", "In winter"], correct: 1 },
      { q: "Which would increase transpiration?", options: ["High humidity", "Low temperature", "Strong wind", "Low light"], correct: 2 },
      { q: "If phloem is damaged, plant will struggle to:", options: ["Absorb water", "Transport sugars", "Exchange gases", "Produce chlorophyll"], correct: 1 },
      { q: "In dehydration, blood becomes:", options: ["More watery", "More concentrated", "Less viscous", "Same"], correct: 1 },
      { q: "Capillary walls are one cell thick to:", options: ["Stop diffusion", "Slow blood", "Allow exchange", "Increase thickness"], correct: 2 }
    ]
  },
  {
    exercise: "Chapter 8: Respiration",
    questions: [
      { q: "Respiration is the process of:", options: ["Taking in oxygen only", "Release of energy by breaking food", "Producing food", "Excreting CO₂"], correct: 1 },
      { q: "Which gas is essential for aerobic respiration?", options: ["N₂", "O₂", "CO₂", "H₂"], correct: 1 },
      { q: "Anaerobic respiration occurs in absence of:", options: ["Water", "Oxygen", "Carbon dioxide", "Nitrogen"], correct: 1 },
      { q: "Energy released in respiration is stored in the form of:", options: ["DNA", "RNA", "ATP", "ADP"], correct: 2 },
      { q: "Which produces more energy per glucose?", options: ["Anaerobic respiration", "Aerobic respiration", "Fermentation only", "Photosynthesis"], correct: 1 },
      { q: "In humans, gaseous exchange takes place in:", options: ["Trachea", "Bronchi", "Alveoli", "Nasal cavity"], correct: 2 },
      { q: "Which muscles are involved in inhalation?", options: ["Abdominal", "Diaphragm & external intercostal", "Heart muscles", "Smooth muscles"], correct: 1 },
      { q: "During inhalation, diaphragm:", options: ["Moves up", "Moves down", "Does not move", "Contracts inward"], correct: 1 },
      { q: "Oxygen is carried in blood mainly by:", options: ["Plasma", "RBCs", "WBCs", "Platelets"], correct: 1 },
      { q: "Which muscle relaxes during exhalation?", options: ["Diaphragm", "Heart", "Biceps", "Liver"], correct: 0 },
      { q: "Plant respiration occurs in:", options: ["Only roots", "Only leaves", "All living cells", "Stem only"], correct: 2 },
      { q: "Which part of the plant stores excess CO₂ during respiration?", options: ["Cell wall", "Vacuole", "Chloroplast", "Mitochondria"], correct: 1 },
      { q: "Aerobic respiration in plants releases:", options: ["Energy + water + CO₂", "Only energy", "Only water", "Only oxygen"], correct: 0 },
      { q: "Anaerobic respiration in plants produces:", options: ["Alcohol & CO₂", "Only water", "Only sugar", "Oxygen"], correct: 0 },
      { q: "Which plants can tolerate low oxygen better?", options: ["Aquatic plants", "Desert plants", "All plants", "None"], correct: 0 },
      { q: "Which of the following respiration types is most efficient?", options: ["Aerobic", "Anaerobic", "Fermentation", "Photosynthesis"], correct: 0 },
      { q: "Anaerobic respiration in humans produces:", options: ["Alcohol", "Lactic acid", "Glucose", "Oxygen"], correct: 1 },
      { q: "Which process occurs continuously all the time?", options: ["Photosynthesis", "Respiration", "Transpiration", "Digestion"], correct: 1 },
      { q: "Gaseous exchange in plants occurs mainly through:", options: ["Xylem", "Stomata", "Lenticels", "Root hairs"], correct: 1 },
      { q: "Which increases during exercise?", options: ["Oxygen uptake", "CO₂ production", "Breathing rate", "All of the above"], correct: 3 },
      { q: "If alveoli surface area decreases, gas exchange will:", options: ["Increase", "Decrease", "Remain same", "Only CO₂ exchange changes"], correct: 1 },
      { q: "A person holding his breath will mainly see an increase in:", options: ["O₂ in blood", "CO₂ in blood", "Glucose in blood", "ATP"], correct: 1 },
      { q: "Anaerobic respiration is useful in:", options: ["Marathon running", "Sprinting", "Resting", "Sleeping"], correct: 1 },
      { q: "Excess lactic acid in muscles causes:", options: ["Pain & fatigue", "Increased energy", "Faster breathing", "Growth"], correct: 0 },
      { q: "Which respiration yields the fastest ATP initially?", options: ["Aerobic", "Anaerobic", "Photosynthesis", "Osmosis"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 9: Plant Reproduction",
    questions: [
      { q: "Asexual reproduction produces offspring that are:", options: ["Genetically identical to parent", "Genetically variable", "Always diploid", "Always haploid"], correct: 0 },
      { q: "Binary fission occurs in:", options: ["Amoeba", "Bacteria", "Fern", "Flowering plant"], correct: 1 },
      { q: "Budding is a form of:", options: ["Sexual reproduction", "Asexual reproduction", "Alternation of generation", "Fragmentation"], correct: 1 },
      { q: "Vegetative propagation produces clones mainly in:", options: ["Animals", "Fungi", "Plants", "Bacteria"], correct: 2 },
      { q: "Tissue culture is used to produce plants that are:", options: ["Genetically diverse", "Genetically uniform", "Always taller", "Only from seeds"], correct: 1 },
      { q: "Which is NOT natural vegetative propagation?", options: ["Runner", "Cutting", "Rhizome", "Tuber"], correct: 1 },
      { q: "Rhizomes are modified:", options: ["Roots", "Stems", "Leaves", "Flowers"], correct: 1 },
      { q: "Which structure stores food and helps in propagation?", options: ["Petiole", "Tuber", "Stigma", "Ovule"], correct: 1 },
      { q: "Strawberry plant propagates by:", options: ["Suckers", "Runner", "Rhizome", "Bulb"], correct: 1 },
      { q: "Bulbs are found in:", options: ["Potato", "Onion", "Banana", "Rose"], correct: 1 },
      { q: "Cutting involves detaching a plant part and rooting it because it contains:", options: ["Embryo", "Meristematic cells", "Chlorophyll", "Seeds"], correct: 1 },
      { q: "Grafting is mainly used to improve:", options: ["Flower colour", "Fruit quality", "Root length", "Seed size"], correct: 1 },
      { q: "Purpose of grafting is to combine:", options: ["Two unrelated species", "Two plant tissues to grow as one", "Seed with fruit", "Root with leaf"], correct: 1 },
      { q: "Tissue culture requires:", options: ["Soil medium", "Sterile lab conditions", "Sunlight only", "Pollination"], correct: 1 },
      { q: "Advantage of tissue culture is that it produces:", options: ["Only one plant", "Large number of plants quickly", "Genetically varied plants", "Seedless propagation only"], correct: 1 },
      { q: "Pollination is the transfer of pollen from:", options: ["Stigma to anther", "Anther to stigma", "Ovary to style", "Root to leaf"], correct: 1 },
      { q: "Self‑pollination occurs when pollen goes from:", options: ["One flower to another plant", "Same flower to its own stigma", "Different species", "Root to flower"], correct: 1 },
      { q: "Cross‑pollination increases:", options: ["Self‑fertilization", "Genetic variation", "Asexual reproduction", "Clone formation"], correct: 1 },
      { q: "Which is a biotic pollination agent?", options: ["Wind", "Water", "Insects", "Gravity"], correct: 2 },
      { q: "The part that becomes seed after fertilization is:", options: ["Ovule", "Stamen", "Petal", "Anther"], correct: 0 },
      { q: "Double fertilization occurs in:", options: ["Moss", "Fern", "Angiosperms", "Gymnosperms"], correct: 2 },
      { q: "The pollen tube grows through:", options: ["Stigma", "Style", "Anther", "Petal"], correct: 1 },
      { q: "Endosperm forms after:", options: ["Single fertilization", "Double fertilization", "Asexual reproduction", "Tissue culture"], correct: 1 },
      { q: "Fruit develops from:", options: ["Ovary", "Anther", "Petal", "Stem"], correct: 0 },
      { q: "Seed dormancy prevents:", options: ["Germination until conditions are favourable", "Fruit formation", "Pollination", "Fertilization"], correct: 0 }
    ]
  },
  {
    exercise: "Chapter 10: Evolution",
    questions: [
      { q: "Evolution is best defined as:", options: ["Sudden event", "Change in genetic characteristics over generations", "Individual growth", "Seasonal change"], correct: 1 },
      { q: "Variation refers to differences among:", options: ["Populations", "Cells only", "Individuals of same species", "Ecosystems"], correct: 2 },
      { q: "Which is a source of variation?", options: ["Natural selection", "Mutations", "Photosynthesis", "Respiration"], correct: 1 },
      { q: "Natural selection acts on:", options: ["Genotypes only", "Phenotypes", "Molecules", "Ecosystems"], correct: 1 },
      { q: "The term “survival of the fittest” refers to:", options: ["Largest individuals", "Best adapted individuals", "Weak ones", "Fast runners"], correct: 1 },
      { q: "Fossils provide information about:", options: ["Future species", "Past organisms", "Only plants", "Only climate"], correct: 1 },
      { q: "Homologous structures indicate:", options: ["Same function but no common ancestry", "Common ancestry but may differ in function", "No evolution", "Same habitat"], correct: 1 },
      { q: "Analogous structures indicate:", options: ["Similar ancestry", "Similar function without common ancestry", "Same DNA", "Identical development"], correct: 1 },
      { q: "Vestigial organs are:", options: ["Fully functional", "Remnants of ancestral structures", "New organs", "Always harmful"], correct: 1 },
      { q: "Comparative anatomy helps in:", options: ["Studying weather", "Understanding evolutionary relationships", "Producing energy", "Digestion"], correct: 1 },
      { q: "Natural selection occurs due to:", options: ["Human choice", "Environment pressures", "Farming", "Breeding"], correct: 1 },
      { q: "Artificial selection is driven by:", options: ["Environment", "Humans", "Predators", "Random chance"], correct: 1 },
      { q: "Which is an example of artificial selection?", options: ["Wild finches", "Domestic dogs bred for traits", "Bacteria in soil", "Trees in forest"], correct: 1 },
      { q: "Natural selection increases:", options: ["Genetic uniformity", "Fitness of organisms", "Immediate change in individuals", "Lifespan only"], correct: 1 },
      { q: "Artificial selection may reduce:", options: ["Human influence", "Genetic diversity", "Variation", "Both B and C"], correct: 3 },
      { q: "Speciation is the process leading to:", options: ["Creation of new species", "Death of all organisms", "Same species reproduction", "Immediate adaptation"], correct: 0 },
      { q: "Allopatric speciation occurs due to:", options: ["Same location", "Physical geographical barrier", "Same food", "Same predators"], correct: 1 },
      { q: "Genetic drift can cause evolution in:", options: ["Large populations", "Small populations", "Only plants", "Ecosystems only"], correct: 1 },
      { q: "Gene flow refers to:", options: ["Movement of genes between populations", "DNA damage", "Cellular respiration", "Same species mating"], correct: 0 },
      { q: "Mutations contribute to evolution by:", options: ["Stopping reproduction", "Creating new alleles", "Destroying DNA", "Reducing variation"], correct: 1 },
      { q: "The primary mechanism of evolution proposed by Darwin is:", options: ["Genetic engineering", "Natural selection", "Speciation", "Mutation"], correct: 1 },
      { q: "Adaptations increase:", options: ["Predation risk", "Survival chances", "Weight only", "Energy loss"], correct: 1 },
      { q: "Which group shows adaptive radiation?", options: ["Finches on Galápagos Islands", "Trees in forest", "Same species fish", "Desert lizards"], correct: 0 },
      { q: "If environment changes rapidly, natural selection:", options: ["Stops", "Favors better adaptation", "Favors identical traits", "Destroys life immediately"], correct: 1 },
      { q: "Evolution acts over:", options: ["Seconds", "Years", "Generations", "Minutes"], correct: 2 }
    ]
  }
];
