export const mdcatLogicalQuizzes = [
  {
    exercise: "Logical Reasoning - Set 1",
    questions: [
      { q: "All doctors are educated. Some educated people are writers. Which conclusion follows?", options: ["All writers are doctors", "Some writers are doctors", "Some educated people are writers", "No doctor is a writer"], correct: 2 },
      { q: "Ali studies every day and scores high marks. What is the best conclusion?", options: ["Every student who studies scores high", "Studying helps improve performance", "Ali is the smartest student", "High marks are impossible without tuition"], correct: 1 },
      { q: "Statement: 'Plants need water to survive.' Conclusion:", options: ["All plants die immediately without water", "Water is essential for plant survival", "Only plants need water", "Water harms plants"], correct: 1 },
      { q: "Every athlete exercises regularly. Ahmed exercises regularly. Choose the correct option:", options: ["Ahmed is definitely an athlete", "Ahmed may or may not be an athlete", "Ahmed is not an athlete", "No conclusion possible"], correct: 1 },
      { q: "Some books are magazines. All magazines are printed. Conclusion:", options: ["Some books are printed", "All books are printed", "No books are printed", "All printed things are books"], correct: 0 },
      { q: "Find the next letter: A, C, E, G, ___", options: ["H", "I", "J", "K"], correct: 1 },
      { q: "Complete the series: 2, 4, 8, 16, ___", options: ["24", "30", "32", "36"], correct: 2 },
      { q: "Find the missing number: 5, 10, 20, 40, ___", options: ["60", "70", "80", "90"], correct: 2 },
      { q: "Complete the sequence: Z, X, V, T, ___", options: ["S", "R", "Q", "D"], correct: 1 },
      { q: "Find the next number: 1, 4, 9, 16, ___", options: ["20", "24", "25", "36"], correct: 2 },
      { q: "All roses are flowers. Some flowers fade quickly. Conclusion:", options: ["All roses fade quickly", "Some roses fade quickly", "Roses are flowers", "No flower fades quickly"], correct: 2 },
      { q: "No bird is a mammal. All sparrows are birds. Conclusion:", options: ["Sparrows are mammals", "Sparrows are not mammals", "Mammals are birds", "All mammals are sparrows"], correct: 1 },
      { q: "Some students are athletes. All athletes are healthy. Conclusion:", options: ["Some students are healthy", "All students are healthy", "No athlete is healthy", "Healthy people are athletes"], correct: 0 },
      { q: "All pens are stationery items. Some stationery items are expensive. Conclusion:", options: ["All pens are expensive", "Some pens may be expensive", "No pen is expensive", "Expensive items are pens"], correct: 1 },
      { q: "No car is a bicycle. Some bicycles are electric. Conclusion:", options: ["Some electric things are not cars", "All cars are electric", "All bicycles are cars", "No bicycle is electric"], correct: 0 },
      { q: "Pointing to a man, Sara said, 'He is the son of my grandfather's only son.' Who is the man?", options: ["Sara's brother", "Sara's uncle", "Sara's father", "Sara's cousin"], correct: 0 },
      { q: "If today is Monday, what day will it be after 10 days?", options: ["Wednesday", "Thursday", "Friday", "Saturday"], correct: 1 },
      { q: "A clock shows 3:15. What is the angle between the hour and minute hands?", options: ["0°", "7.5°", "15°", "22.5°"], correct: 1 },
      { q: "If CAT = 24, DOG = 26, then BAT = ?", options: ["21", "22", "23", "24"], correct: 2 },
      { q: "A man walks 5 km north, then 5 km east. How far is he from the starting point?", options: ["5 km", "7.07 km", "10 km", "12 km"], correct: 1 },
      { q: "Statement I: Heavy rain occurred in the city. Statement II: Roads became flooded.", options: ["I is the cause of II", "II is the cause of I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement I: Students studied hard. Statement II: Examination results improved.", options: ["I causes II", "II causes I", "Both unrelated", "Neither"], correct: 0 },
      { q: "Statement I: Electricity supply failed. Statement II: Factories stopped working.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement I: Trees were cut down rapidly. Statement II: Temperature increased in the area.", options: ["II causes I", "I causes II", "Both independent", "No relation"], correct: 1 },
      { q: "Statement I: The patient took medicine regularly. Statement II: The patient recovered quickly.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement: 'Traffic accidents are increasing.' Courses of Action:", options: ["Only I", "Only II", "Both I and II", "Neither"], correct: 2 },
      { q: "Statement: 'Water shortage is worsening.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Air pollution is increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Students are weak in mathematics.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 0 },
      { q: "Statement: 'Food prices are rising rapidly.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 }
    ]
  },
  {
    exercise: "Logical Reasoning - Set 2",
    questions: [
      { q: "All nurses are trained professionals. Some trained professionals work at clinics. Conclusion:", options: ["All clinic workers are nurses", "Some nurses work at clinics", "Nurses are trained professionals", "No trained professional works at clinics"], correct: 2 },
      { q: "Statement: 'Exercise improves physical health.' Which statement is correct?", options: ["Exercise has no effect on health", "Physical health can improve through exercise", "Only athletes should exercise", "Exercise is harmful"], correct: 1 },
      { q: "Every laptop is an electronic device. Some electronic devices are expensive. Conclusion:", options: ["All laptops are expensive", "Some laptops may be expensive", "No laptop is expensive", "Expensive things are laptops"], correct: 1 },
      { q: "Ali always arrives on time to school. What can be concluded?", options: ["Ali is punctual", "Ali never studies", "Ali lives near school", "Ali is a teacher"], correct: 0 },
      { q: "All apples are fruits. Some fruits are sweet. Conclusion:", options: ["All apples are sweet", "Some apples are sweet", "Apples are fruits", "No fruit is sweet"], correct: 2 },
      { q: "Find the next number: 3, 6, 12, 24, ___", options: ["36", "42", "48", "54"], correct: 2 },
      { q: "Complete the sequence: B, D, F, H, ___", options: ["I", "J", "K", "D"], correct: 1 },
      { q: "Find the next number: 100, 90, 80, 70, ___", options: ["65", "60", "50", "55"], correct: 1 },
      { q: "Complete the series: 1, 8, 27, 64, ___", options: ["100", "121", "125", "144"], correct: 2 },
      { q: "Find the missing letter: M, O, Q, S, ___", options: ["T", "U", "V", "W"], correct: 1 },
      { q: "All teachers are educated. Some educated people are writers. Conclusion:", options: ["Some teachers are writers", "Teachers are educated", "All writers are teachers", "No writer is educated"], correct: 1 },
      { q: "No fish can fly. Some birds can fly. Conclusion:", options: ["Birds are fish", "Fish cannot fly", "All birds are fish", "Flying things are fish"], correct: 1 },
      { q: "All cars have wheels. Some vehicles are cars. Conclusion:", options: ["Some vehicles have wheels", "All vehicles are cars", "No car has wheels", "Wheels are vehicles"], correct: 0 },
      { q: "Some students are intelligent. All intelligent people work hard. Conclusion:", options: ["Some students work hard", "All students work hard", "No intelligent person works hard", "Hardworking people are students"], correct: 0 },
      { q: "All cats are animals. No animal is a plant. Conclusion:", options: ["Cats are not plants", "Plants are cats", "Animals are plants", "Some plants are animals"], correct: 0 },
      { q: "A boy is introduced as 'the son of the daughter of my mother.' Who is the boy?", options: ["Brother", "Nephew", "Son", "Cousin"], correct: 2 },
      { q: "If today is Friday, what day will it be after 15 days?", options: ["Friday", "Saturday", "Sunday", "Monday"], correct: 1 },
      { q: "A train travels 60 km in 1 hour. How far will it travel in 4 hours?", options: ["180 km", "200 km", "240 km", "260 km"], correct: 2 },
      { q: "If PEN = 35 and BOOK = 43, then BAG = ?", options: ["12", "14", "10", "9"], correct: 2 },
      { q: "A man walks 4 km south and then 3 km west. How far is he from the starting point?", options: ["4 km", "5 km", "6 km", "7 km"], correct: 1 },
      { q: "Statement I: The road was slippery. Statement II: Several cars skidded.", options: ["I causes II", "II causes I", "Both unrelated", "No relation"], correct: 0 },
      { q: "Statement I: The student practiced daily. Statement II: She became better at mathematics.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: A severe storm hit the village. Statement II: Electricity poles were damaged.", options: ["II causes I", "I causes II", "Both independent", "No relation"], correct: 1 },
      { q: "Statement I: Factories released toxic smoke. Statement II: Air quality worsened.", options: ["I causes II", "II causes I", "Both unrelated", "No relation"], correct: 0 },
      { q: "Statement I: The patient ignored medical advice. Statement II: His condition worsened.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement: 'Students spend too much time on social media.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 0 },
      { q: "Statement: 'Road traffic is increasing rapidly.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'People are wasting electricity.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Many children are unhealthy.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Internet fraud cases are increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 }
    ]
  },
  {
    exercise: "Logical Reasoning - Set 3",
    questions: [
      { q: "All engineers are educated. Some educated people are scientists. Conclusion:", options: ["All scientists are engineers", "Some engineers are scientists", "Engineers are educated", "No scientist is educated"], correct: 2 },
      { q: "Statement: 'Healthy eating reduces disease risk.' Which statement is correct?", options: ["Healthy eating may improve health", "Diseases cannot be prevented", "Only sick people should eat healthy food", "Healthy food causes disease"], correct: 0 },
      { q: "All mobile phones are electronic devices. Some electronic devices are portable. Conclusion:", options: ["All mobile phones are portable", "Some mobile phones may be portable", "No mobile phone is portable", "Portable devices are phones"], correct: 1 },
      { q: "Sara reads books daily. What can be concluded?", options: ["Sara likes reading", "Sara dislikes books", "Sara is a librarian", "Sara never studies"], correct: 0 },
      { q: "Some pencils are colored. All colored objects are attractive. Conclusion:", options: ["Some pencils are attractive", "All pencils are attractive", "No pencil is attractive", "Attractive things are pencils"], correct: 0 },
      { q: "Find the next number: 7, 14, 21, 28, ___", options: ["30", "32", "35", "42"], correct: 2 },
      { q: "Complete the sequence: C, F, I, L, ___", options: ["N", "O", "P", "Q"], correct: 1 },
      { q: "Find the missing number: 1, 3, 6, 10, 15, ___", options: ["18", "20", "21", "24"], correct: 2 },
      { q: "Complete the series: A, D, G, J, ___", options: ["K", "L", "M", "N"], correct: 2 },
      { q: "Find the next number: 81, 64, 49, 36, ___", options: ["16", "20", "25", "30"], correct: 2 },
      { q: "All lions are animals. Some animals are dangerous. Conclusion:", options: ["All lions are dangerous", "Some lions are dangerous", "Lions are animals", "Dangerous things are lions"], correct: 2 },
      { q: "No student is absent today. Ali is a student. Conclusion:", options: ["Ali is absent", "Ali is present", "Ali is a teacher", "No conclusion"], correct: 1 },
      { q: "All flowers need water. Rose is a flower. Conclusion:", options: ["Rose needs water", "All flowers are roses", "Water is a flower", "Roses do not need water"], correct: 0 },
      { q: "Some doctors are surgeons. All surgeons are skilled. Conclusion:", options: ["Some doctors are skilled", "All doctors are skilled", "No surgeon is skilled", "Skilled people are doctors"], correct: 0 },
      { q: "All buses are vehicles. No vehicle is a tree. Conclusion:", options: ["Buses are not trees", "Trees are buses", "Vehicles are trees", "Some trees are vehicles"], correct: 0 },
      { q: "Pointing to a woman, Ahmed said, 'She is the daughter of my mother's sister.' Who is the woman?", options: ["Mother", "Aunt", "Cousin", "Sister"], correct: 2 },
      { q: "If today is Sunday, what day will it be after 20 days?", options: ["Friday", "Saturday", "Sunday", "Monday"], correct: 1 },
      { q: "A car moves at 80 km/h. How far will it travel in 3 hours?", options: ["200 km", "220 km", "240 km", "260 km"], correct: 2 },
      { q: "If APPLE = 50 and ORANGE = 60, then MANGO = ?", options: ["45", "50", "55", "65"], correct: 2 },
      { q: "A person walks 6 km east and then 8 km north. How far is the person from the starting point?", options: ["10 km", "12 km", "14 km", "15 km"], correct: 0 },
      { q: "Statement I: The driver was careless. Statement II: The car crashed.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement I: The weather became extremely cold. Statement II: People wore warm clothes.", options: ["I causes II", "II causes I", "Both unrelated", "Neither"], correct: 0 },
      { q: "Statement I: Heavy snowfall blocked roads. Statement II: Traffic was delayed.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement I: Farmers used better fertilizers. Statement II: Crop production increased.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement I: The company reduced prices. Statement II: Sales increased.", options: ["I causes II", "II causes I", "Both independent", "No relation"], correct: 0 },
      { q: "Statement: 'Many people suffer from obesity.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 0 },
      { q: "Statement: 'Public parks are becoming dirty.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Students are performing poorly in science.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Water pollution is increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Cyberbullying cases are increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 }
    ]
  },
  {
    exercise: "Logical Reasoning - Set 4",
    questions: [
      { q: "All pharmacists study medicine. Some medical students are researchers. Conclusion:", options: ["All researchers are pharmacists", "Some pharmacists are researchers", "Pharmacists study medicine", "No researcher studies medicine"], correct: 2 },
      { q: "Statement: 'Regular sleep improves concentration.' Which statement is correct?", options: ["Sleep has no effect on concentration", "Proper sleep may help concentration", "Only students need sleep", "Concentration decreases with sleep"], correct: 1 },
      { q: "All tablets are electronic gadgets. Some electronic gadgets are costly. Conclusion:", options: ["All tablets are costly", "Some tablets may be costly", "No tablet is costly", "Costly gadgets are tablets"], correct: 1 },
      { q: "Hamza practices football every evening. What can be concluded?", options: ["Hamza is interested in football", "Hamza dislikes sports", "Hamza is a coach", "Hamza never studies"], correct: 0 },
      { q: "Some cars are fast. All fast things require control. Conclusion:", options: ["Some cars require control", "All cars require control", "No car requires control", "Controlled things are cars"], correct: 0 },
      { q: "Find the next number: 9, 18, 27, 36, ___", options: ["40", "45", "48", "54"], correct: 1 },
      { q: "Complete the sequence: D, G, J, M, ___", options: ["O", "P", "Q", "R"], correct: 2 },
      { q: "Find the missing number: 2, 5, 10, 17, 26, ___", options: ["35", "36", "37", "38"], correct: 2 },
      { q: "Complete the series: Z, W, T, Q, ___", options: ["N", "O", "P", "M"], correct: 0 },
      { q: "Find the next number: 2, 6, 12, 20, ___", options: ["28", "30", "32", "36"], correct: 1 },
      { q: "All mangoes are fruits. Some fruits are juicy. Conclusion:", options: ["All mangoes are juicy", "Some mangoes are juicy", "Mangoes are fruits", "Juicy things are mangoes"], correct: 2 },
      { q: "No reptile is warm-blooded. Snake is a reptile. Conclusion:", options: ["Snake is warm-blooded", "Snake is not warm-blooded", "All reptiles are snakes", "No conclusion"], correct: 1 },
      { q: "All nurses help patients. Sara is a nurse. Conclusion:", options: ["Sara helps patients", "Sara is a doctor", "Patients are nurses", "Nurses are patients"], correct: 0 },
      { q: "Some athletes are swimmers. All swimmers exercise regularly. Conclusion:", options: ["Some athletes exercise regularly", "All athletes exercise regularly", "No swimmer exercises", "Exercising people are athletes"], correct: 0 },
      { q: "All planets revolve around the sun. Earth is a planet. Conclusion:", options: ["Earth revolves around the sun", "Sun revolves around Earth", "All planets are Earth", "Earth is not a planet"], correct: 0 },
      { q: "Pointing to a boy, Fatima said, 'He is the son of my father's brother.' Who is the boy?", options: ["Brother", "Cousin", "Uncle", "Nephew"], correct: 1 },
      { q: "If today is Tuesday, what day will it be after 12 days?", options: ["Sunday", "Monday", "Tuesday", "Wednesday"], correct: 1 },
      { q: "A bus travels 50 km in 1 hour. How far will it travel in 5 hours?", options: ["200 km", "220 km", "250 km", "300 km"], correct: 2 },
      { q: "If BOOK = 41 and PEN = 35, then COPY = ?", options: ["45", "50", "55", "60"], correct: 1 },
      { q: "A person walks 9 km west and then 12 km north. How far is the person from the starting point?", options: ["12 km", "15 km", "18 km", "21 km"], correct: 1 },
      { q: "Statement I: The patient followed the doctor's advice. Statement II: The patient recovered quickly.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: Fuel prices increased. Statement II: Transport fares increased.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: A power outage occurred. Statement II: Factories stopped production.", options: ["I causes II", "II causes I", "Both unrelated", "No relation"], correct: 0 },
      { q: "Statement I: Students attended revision classes. Statement II: Test scores improved.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: Roads were repaired. Statement II: Traffic flow improved.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement: 'Many students fail due to poor time management.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 0 },
      { q: "Statement: 'Plastic waste is increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Road accidents are common at night.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Children spend little time reading books.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Internet addiction among teenagers is increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 }
    ]
  },
  {
    exercise: "Logical Reasoning - Set 5",
    questions: [
      { q: "All surgeons are doctors. Some doctors work in private hospitals. Conclusion:", options: ["All surgeons work in private hospitals", "Some surgeons work in private hospitals", "Surgeons are doctors", "No doctor works in hospitals"], correct: 2 },
      { q: "Statement: 'Daily exercise strengthens muscles.' Which statement is correct?", options: ["Exercise weakens muscles", "Exercise may improve muscle strength", "Only athletes need exercise", "Muscles are unrelated to exercise"], correct: 1 },
      { q: "All cameras are devices. Some devices are portable. Conclusion:", options: ["All cameras are portable", "Some cameras may be portable", "No camera is portable", "Portable things are cameras"], correct: 1 },
      { q: "Usman practices mathematics every day. What can be concluded?", options: ["Usman wants to improve in mathematics", "Usman dislikes mathematics", "Usman is a teacher", "Usman never studies"], correct: 0 },
      { q: "Some birds can swim. All swimming animals need energy. Conclusion:", options: ["Some birds need energy", "All birds need energy", "No birds need energy", "Energy is a bird"], correct: 0 },
      { q: "Find the next number: 11, 22, 33, 44, ___", options: ["50", "55", "60", "66"], correct: 1 },
      { q: "Complete the sequence: E, H, K, N, ___", options: ["P", "Q", "R", "S"], correct: 1 },
      { q: "Find the missing number: 4, 9, 16, 25, 36, ___", options: ["42", "45", "49", "64"], correct: 2 },
      { q: "Complete the series: Y, V, S, P, ___", options: ["M", "N", "O", "D"], correct: 0 },
      { q: "Find the next number: 3, 9, 27, 81, ___", options: ["162", "243", "324", "729"], correct: 1 },
      { q: "All apples are healthy foods. Some healthy foods are expensive. Conclusion:", options: ["All apples are expensive", "Some apples are expensive", "Apples are healthy foods", "Expensive things are apples"], correct: 2 },
      { q: "No insect is a mammal. Butterfly is an insect. Conclusion:", options: ["Butterfly is a mammal", "Butterfly is not a mammal", "Mammals are insects", "No conclusion"], correct: 1 },
      { q: "All teachers guide students. Mr. Ali is a teacher. Conclusion:", options: ["Mr. Ali guides students", "Mr. Ali is a student", "Students are teachers", "Teachers are students"], correct: 0 },
      { q: "Some musicians are singers. All singers practice regularly. Conclusion:", options: ["Some musicians practice regularly", "All musicians practice regularly", "No singer practices", "Practicing people are singers"], correct: 0 },
      { q: "All computers use electricity. Laptop is a computer. Conclusion:", options: ["Laptop uses electricity", "Electricity uses laptops", "Computers are laptops", "Laptop is not a computer"], correct: 0 },
      { q: "Pointing to a girl, Bilal said, 'She is the daughter of my mother's daughter.' Who is the girl?", options: ["Sister", "Daughter", "Cousin", "Niece"], correct: 3 },
      { q: "If today is Wednesday, what day will it be after 9 days?", options: ["Thursday", "Friday", "Saturday", "Sunday"], correct: 1 },
      { q: "A cyclist rides 15 km in 1 hour. How far will the cyclist ride in 6 hours?", options: ["75 km", "80 km", "90 km", "100 km"], correct: 2 },
      { q: "If CAR = 24 and BUS = 42, then VAN = ?", options: ["35", "37", "39", "41"], correct: 2 },
      { q: "A person walks 5 km east and then 12 km south. How far is the person from the starting point?", options: ["12 km", "13 km", "15 km", "17 km"], correct: 1 },
      { q: "Statement I: The student revised thoroughly. Statement II: The student passed the exam with high marks.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: The city received heavy rainfall. Statement II: Streets were flooded.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: The factory installed modern machines. Statement II: Production increased.", options: ["I causes II", "II causes I", "Both unrelated", "No relation"], correct: 0 },
      { q: "Statement I: Trees were planted in the city. Statement II: Air quality improved.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement I: Students attended science workshops. Statement II: Their understanding improved.", options: ["I causes II", "II causes I", "No relation", "Both independent"], correct: 0 },
      { q: "Statement: 'Many people suffer from stress.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'The number of road accidents is increasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'School attendance is decreasing.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Noise pollution is rising in cities.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 },
      { q: "Statement: 'Waterborne diseases are spreading.' Courses of Action:", options: ["Only I", "Only II", "Both", "Neither"], correct: 2 }
    ]
  }
];
