export const physicsClass12Quizzes = [
  {
    exercise: "Chapter 1: Electrostatics",
    questions: [
      { q: "Two charges +q and +4q are placed at distance r. Where is net field zero?", options: ["Between them", "Closer to +q", "Closer to +4q", "Outside"], correct: 1 },
      { q: "A charge is doubled and distance halved. Force becomes:", options: ["Same", "2×", "4×", "8×"], correct: 3 },
      { q: "Electric field at center of a uniformly charged ring is:", options: ["Maximum", "Minimum", "Zero", "Infinite"], correct: 2 },
      { q: "Work done in moving charge in closed path in electrostatics:", options: ["Positive", "Negative", "Zero", "Infinite"], correct: 2 },
      { q: "Two identical charges repel with force F. If one becomes half:", options: ["F/2", "F/4", "F/8", "2F"], correct: 0 },
      { q: "Electric potential is constant in a region. Field is:", options: ["Maximum", "Zero", "Infinite", "Variable"], correct: 1 },
      { q: "A proton is released in uniform field. Its motion is:", options: ["Circular", "Uniform", "Accelerated", "Oscillatory"], correct: 2 },
      { q: "Potential energy of two like charges:", options: ["Negative", "Zero", "Positive", "Infinite"], correct: 2 },
      { q: "Field lines density represents:", options: ["Charge", "Potential", "Field strength", "Energy"], correct: 2 },
      { q: "Electric field inside charged hollow conductor:", options: ["Non-zero", "Zero", "Maximum", "Depends"], correct: 1 },
      { q: "If dielectric constant increases, capacitance:", options: ["Decreases", "Increases", "Zero", "Infinite"], correct: 1 },
      { q: "Capacitance depends on:", options: ["Charge", "Voltage", "Geometry", "Energy"], correct: 2 },
      { q: "Potential due to dipole at far point varies as:", options: ["1/r", "1/r²", "1/r³", "Constant"], correct: 2 },
      { q: "Torque on dipole is maximum when angle is:", options: ["0°", "45°", "90°", "180°"], correct: 2 },
      { q: "Electric flux through surface depends on:", options: ["Shape", "Orientation", "Enclosed charge", "Area only"], correct: 2 },
      { q: "A charge inside cube. Flux depends on:", options: ["Position", "Size", "Charge", "Shape"], correct: 2 },
      { q: "Field due to infinite sheet:", options: ["Depends on distance", "Constant", "Zero", "Infinite"], correct: 1 },
      { q: "If distance increases 3 times, potential becomes:", options: ["1/3", "1/9", "3", "9"], correct: 0 },
      { q: "Capacitance of isolated sphere increases if:", options: ["Radius increases", "Charge increases", "Voltage increases", "Energy increases"], correct: 0 },
      { q: "Two capacitors in series:", options: ["Same charge", "Same voltage", "Same energy", "None"], correct: 0 },
      { q: "Energy stored in capacitor:", options: ["CV", "½CV²", "QV", "½QV"], correct: 1 },
      { q: "Electric field is gradient of:", options: ["Charge", "Potential", "Flux", "Energy"], correct: 1 },
      { q: "Potential difference between two points same surface:", options: ["Zero", "Infinite", "Maximum", "Variable"], correct: 0 },
      { q: "Charge quantization implies:", options: ["Continuous", "Discrete", "Infinite", "Zero"], correct: 1 },
      { q: "Electric field lines are perpendicular to:", options: ["Charge", "Surface", "Equipotential", "Current"], correct: 2 },
      { q: "Two opposite charges form:", options: ["Capacitor", "Dipole", "Field", "Flux"], correct: 1 },
      { q: "If electric field is zero, potential:", options: ["Must be zero", "Constant", "Infinite", "Variable"], correct: 1 },
      { q: "A capacitor stores 2J energy at 10V. Capacitance is:", options: ["0.02F", "0.04F", "0.1F", "0.2F"], correct: 1 },
      { q: "Charge on capacitor Q = 20C, V = 10V. C = ?", options: ["1F", "2F", "3F", "0.5F"], correct: 1 },
      { q: "Force between charges in medium decreases because:", options: ["k increases", "ε increases", "q decreases", "r increases"], correct: 1 },
      { q: "Electric field of point charge is:", options: ["Uniform", "Radial", "Circular", "Linear"], correct: 1 },
      { q: "Potential energy decreases when:", options: ["Like charges approach", "Opposite charges approach", "Distance increases", "Charge decreases"], correct: 1 },
      { q: "Electric field at midpoint of equal opposite charges:", options: ["Zero", "Double", "Infinite", "Maximum"], correct: 1 },
      { q: "Field inside capacitor plates:", options: ["Zero", "Uniform", "Circular", "Variable"], correct: 1 },
      { q: "Unit of permittivity:", options: ["F/m", "N/C", "Volt", "Joule"], correct: 0 },
      { q: "If area doubles, capacitance:", options: ["Doubles", "Halves", "Same", "Zero"], correct: 0 },
      { q: "Electric field lines are:", options: ["Closed", "Open", "Circular", "Random"], correct: 1 },
      { q: "Potential due to charge at infinity:", options: ["Zero", "Infinite", "Maximum", "Minimum"], correct: 0 },
      { q: "Capacitance independent of:", options: ["Geometry", "Medium", "Charge", "Area"], correct: 2 },
      { q: "Dipole in uniform field experiences:", options: ["Force", "Torque", "Both", "None"], correct: 1 },
      { q: "Flux through plane surface:", options: ["EA", "EA cosθ", "EA sinθ", "E/A"], correct: 1 },
      { q: "Electric field due to sphere outside:", options: ["kq/r²", "q/r", "Constant", "Zero"], correct: 0 },
      { q: "Potential inside conductor:", options: ["Zero", "Constant", "Infinite", "Variable"], correct: 1 },
      { q: "Electric field inside dielectric:", options: ["Increases", "Decreases", "Same", "Zero"], correct: 1 },
      { q: "If voltage increases, capacitance:", options: ["Increases", "Decreases", "Same", "Zero"], correct: 2 },
      { q: "Two capacitors parallel:", options: ["Voltage same", "Charge same", "Energy same", "None"], correct: 0 },
      { q: "Field at edge of charged conductor:", options: ["Zero", "Maximum", "Minimum", "Same"], correct: 1 },
      { q: "Potential difference is:", options: ["Scalar", "Vector", "Tensor", "None"], correct: 0 },
      { q: "Work done moving charge perpendicular to field:", options: ["Zero", "Maximum", "Infinite", "Negative"], correct: 0 },
      { q: "Electric field strength is maximum where lines are:", options: ["Far apart", "Close", "Curved", "Straight"], correct: 1 }
    ]
  },
  {
    exercise: "Chapter 2: Current Electricity",
    questions: [
      { q: "A wire carries current. Drift velocity is small because:", options: ["Charge is small", "Collisions occur frequently", "Field is zero", "Resistance is zero"], correct: 1 },
      { q: "If electric field in a conductor increases, drift velocity:", options: ["Decreases", "Increases", "Zero", "Constant"], correct: 1 },
      { q: "Two wires same material, one twice length. Resistance:", options: ["Same", "Double", "Half", "Four times"], correct: 1 },
      { q: "Two wires same length, one double radius. Resistance:", options: ["Same", "Double", "Half", "One-fourth"], correct: 3 },
      { q: "Current is same in all parts of series circuit because:", options: ["Voltage same", "Charge conservation", "Resistance same", "Power same"], correct: 1 },
      { q: "In parallel circuit, current divides because:", options: ["Voltage same", "Resistance differs", "Charge lost", "Power lost"], correct: 1 },
      { q: "Potential difference exists due to:", options: ["Electric field", "Charge", "Resistance", "Energy"], correct: 0 },
      { q: "If temperature increases, resistance of metal:", options: ["Decreases", "Increases", "Same", "Zero"], correct: 1 },
      { q: "Resistivity changes with:", options: ["Length", "Area", "Temperature", "Voltage"], correct: 2 },
      { q: "If length doubles and area halves, resistance:", options: ["Same", "Double", "Four times", "Half"], correct: 2 },
      { q: "Power dissipated is maximum when:", options: ["R = r", "R = 0", "R = ∞", "R = 2r"], correct: 0 },
      { q: "EMF is maximum when current is:", options: ["Zero", "Maximum", "Half", "Infinite"], correct: 0 },
      { q: "Terminal voltage decreases when:", options: ["Current increases", "Resistance increases", "EMF increases", "Power increases"], correct: 0 },
      { q: "A cell is short-circuited. Current is:", options: ["Zero", "Maximum", "Minimum", "Infinite"], correct: 1 },
      { q: "Drift velocity is opposite to:", options: ["Current", "Electric field", "Voltage", "Resistance"], correct: 1 },
      { q: "Current density depends on:", options: ["Area", "Current", "Both", "None"], correct: 2 },
      { q: "If current doubles, heat produced:", options: ["Same", "Double", "Four times", "Half"], correct: 2 },
      { q: "In Ohmic conductor, V-I graph is:", options: ["Linear", "Curve", "Circle", "Random"], correct: 0 },
      { q: "Non-ohmic device example:", options: ["Copper wire", "Resistor", "Diode", "Metal"], correct: 2 },
      { q: "If voltage doubles, current:", options: ["Same", "Double", "Half", "Zero"], correct: 1 },
      { q: "Electric field in wire depends on:", options: ["Voltage", "Length", "Both", "None"], correct: 2 },
      { q: "If resistance increases, current:", options: ["Increases", "Decreases", "Same", "Zero"], correct: 1 },
      { q: "Energy lost per charge is:", options: ["Voltage", "Current", "Power", "Resistance"], correct: 0 },
      { q: "If wire stretched, resistance:", options: ["Decreases", "Increases", "Same", "Zero"], correct: 1 },
      { q: "Kirchhoff’s current law based on:", options: ["Energy conservation", "Charge conservation", "Power law", "Ohm’s law"], correct: 1 },
      { q: "Kirchhoff’s voltage law based on:", options: ["Charge conservation", "Energy conservation", "Current law", "Resistance"], correct: 1 },
      { q: "If two resistors are equal in parallel, equivalent:", options: ["Same", "Double", "Half", "Zero"], correct: 2 },
      { q: "A 10Ω resistor has 2A current. Voltage:", options: ["5V", "10V", "20V", "40V"], correct: 2 },
      { q: "Power in above resistor:", options: ["10W", "20W", "40W", "80W"], correct: 3 },
      { q: "A wire carries 3A for 10s. Charge:", options: ["10C", "20C", "30C", "40C"], correct: 2 },
      { q: "If internal resistance increases, terminal voltage:", options: ["Increases", "Decreases", "Same", "Zero"], correct: 1 },
      { q: "Current through battery depends on:", options: ["EMF", "Resistance", "Both", "None"], correct: 2 },
      { q: "If area increases, current density:", options: ["Increases", "Decreases", "Same", "Zero"], correct: 1 },
      { q: "Mobility increases if:", options: ["Collisions increase", "Temperature decreases", "Field decreases", "Mass increases"], correct: 1 },
      { q: "Resistance of superconductor:", options: ["High", "Zero", "Infinite", "Variable"], correct: 1 },
      { q: "Electric power unit is:", options: ["J/s", "J", "V", "A"], correct: 0 },
      { q: "A 100W bulb runs for 10s. Energy:", options: ["100J", "500J", "1000J", "2000J"], correct: 2 },
      { q: "If voltage constant, increasing resistance:", options: ["Increases power", "Decreases power", "Same", "Zero"], correct: 1 },
      { q: "Equivalent resistance in series is always:", options: ["Less", "Greater", "Same", "Zero"], correct: 1 },
      { q: "Equivalent resistance in parallel:", options: ["Greater", "Less", "Same", "Infinite"], correct: 1 },
      { q: "If wire length increases, drift velocity:", options: ["Same", "Decreases", "Increases", "Zero"], correct: 1 },
      { q: "Electric field direction is:", options: ["Electron motion", "Opposite electron motion", "Same current", "Random"], correct: 1 },
      { q: "Current flows due to:", options: ["Potential difference", "Resistance", "Charge", "Field only"], correct: 0 },
      { q: "Heating effect depends on:", options: ["I²", "R", "Time", "All"], correct: 3 },
      { q: "If two cells in series, EMF:", options: ["Adds", "Decreases", "Same", "Zero"], correct: 0 },
      { q: "If two cells in parallel, EMF:", options: ["Adds", "Same", "Decreases", "Zero"], correct: 1 },
      { q: "A conductor with zero field has:", options: ["No current", "Maximum current", "Infinite current", "Random"], correct: 0 },
      { q: "Voltage drop across resistor:", options: ["IR", "V/R", "I/R", "None"], correct: 0 },
      { q: "Work done per unit charge:", options: ["Voltage", "Current", "Power", "Resistance"], correct: 0 },
      { q: "Maximum power transfer occurs when:", options: ["R = r", "R = 0", "R = ∞", "R = 2r"], correct: 0 }
    ]
  },
  {
    exercise: "Chapter 3: Magnetic Field of Current",
    questions: [
      { q: "Magnetic field is produced by:", options: ["Stationary charges", "Moving charges", "Neutrons", "Electric field only"], correct: 1 },
      { q: "Unit of magnetic field:", options: ["Tesla", "Weber", "Henry", "Volt"], correct: 0 },
      { q: "Force on moving charge depends on:", options: ["Velocity", "Magnetic field", "Charge", "All"], correct: 3 },
      { q: "If velocity is parallel to field, force is:", options: ["Maximum", "Zero", "Infinite", "Half"], correct: 1 },
      { q: "Direction of force is given by:", options: ["Right-hand rule", "Left-hand rule", "Fleming’s rule", "None"], correct: 1 },
      { q: "Magnetic force does no work because:", options: ["It is zero", "Perpendicular to motion", "Parallel", "Infinite"], correct: 1 },
      { q: "Magnetic field around wire:", options: ["Straight", "Circular", "Random", "Zero"], correct: 1 },
      { q: "Field strength increases with:", options: ["Distance", "Current", "Radius", "Time"], correct: 1 },
      { q: "Two parallel currents same direction:", options: ["Repel", "Attract", "Zero", "Infinite"], correct: 1 },
      { q: "Opposite currents:", options: ["Attract", "Repel", "Zero", "Same"], correct: 1 }
    ]
  }
];
